create table public.db_optimizer (
     match_driver                                           text                null 
    ,confidence_code                                        int                 null 
    ,match_grade                                            text                null 
    ,match_profile                                          text                null 
    ,duplicate_company                                      text                null 
    ,duns_number                                            bigint              not null 
    ,business_name                                          text                null 
    ,location_type                                          text                null 
    ,web_address                                            text                null 
    ,bamfab_marketability                                   text                null 
    ,tradestyle_name                                        text                null 
    ,telephone_number                                       text                null 
    ,year_started                                           int                 null 
    ,public_private_indicator                               char                null 
    ,fax_number                                             text                null 
    ,small_business_indicator                               char                null 
    ,minority_owned_indicator                               char                null 
    ,owns_rents_code                                        smallint            null 
    ,square_footage                                         int                 null 
    ,subsidiary_indicator                                   smallint            null 
    ,manufacturing_indicator                                smallint            null 
    ,legal_status_code                                      smallint            null 
    ,import_export_agent_code                               char                null 
    ,accounting_firm_name                                   text                null 
    ,currency_code                                          text                null 
    ,status_code                                            smallint            null 
    ,population_code                                        smallint            null 
    ,site_status                                            smallint            null 
    ,hierarchy_code                                         smallint            null 
    ,dias_code                                              int                 null 
    ,last_update_date                                       int                 null 
    ,national_identification_number                         bigint              null 
    ,primary_local_activity_code                            text                null 
    ,street_address                                         text                null 
    ,street_address_2                                       text                null 
    ,city_name                                              text                null 
    ,state_province_abbreviation                            char(2)             null 
    ,state_province_name                                    text                null 
    ,postal_code                                            text                null 
    ,county_name                                            text                null 
    ,site_iso_country_code                                  char(2)             null 
    ,country_region_code                                    text                null 
    ,country_region_name                                    text                null 
    ,latitude                                               text                null 
    ,longitude                                              text                null 
    ,mailing_address                                        text                null 
    ,mailing_address_2                                      text                null 
    ,mailing_city_name                                      text                null 
    ,mailing_state_province_abbreviation                    text                null 
    ,mailing_postal_code                                    text                null 
    ,carrier_route_code                                     text                null 
    ,geo_cdoe_accuracy                                      char                null 
    ,latitude_short                                         text                null 
    ,longitude_short                                        text                null 
    ,db_continent_code                                      smallint            null 
    ,db_country_region_code                                 smallint            null 
    ,db_state_code                                          smallint            null 
    ,db_city_code                                           smallint            null 
    ,db_us_county_code                                      smallint            null 
    ,smsa_code                                              smallint            null 
    ,fips_country_region_code                               text                null 
    ,fips_state_code                                        smallint            null 
    ,fips_county_code                                       int                 null 
    ,fips_msa_code                                          int                 null 
    ,country_region_access_code                             smallint            null 
    ,employees_here                                         int                 null 
    ,employee_count_total                                   int                 null 
    ,employee_count_range                                   text                null 
    ,revenue_us_dollars                                     bigint              null 
    ,revenue_range                                          text                null 
    ,employee_count_trend_year                              int                 null 
    ,employee_count_3_year_base                             int                 null 
    ,employee_count_3_year_growth_percentage                int                 null 
    ,employee_count_5_year_base                             int                 null 
    ,employee_count_5_year_growth_percentage                int                 null 
    ,employee_count_total_reliability_code                  smallint            null 
    ,employee_count_here_reliability_code                   smallint            null 
    ,revenue_local_currency                                 bigint              null 
    ,revenue_trend_year                                     bigint              null 
    ,revenue_3_year_base                                    bigint              null 
    ,revenue_3_year_growth_percentage                       int                 null 
    ,revenue_5_year_base                                    bigint              null 
    ,revenue_5_year_growth_percentage                       int                 null 
    ,revenue_local_currency_reliability_code                smallint            null 
    ,domestic_ultimate_duns_number                          bigint              null 
    ,domestic_ultimate_business_name                        text                null 
    ,global_ultimate_duns_number                            bigint              null 
    ,global_ultimate_business_name                          text                null 
    ,number_of_family_members                               int                 null 
    ,parent_duns_number                                     bigint              null 
    ,domestic_ultimate_employee_count                       int                 null 
    ,domestic_ultimate_revenue                              bigint              null 
    ,domestic_ultimate_employee_range                       text                null 
    ,domestic_ultimate_revenue_range                        text                null 
    ,domestic_ultimate_street_address                       text                null 
    ,domestic_ultimate_city                                 text                null 
    ,domestic_ultimate_postal_code                          text                null 
    ,domestic_ultimate_iso_country_code                     char(2)             null 
    ,domestic_ultimate_fips_country_region_code             text                null 
    ,domestic_ultimate_db_country_region_code               smallint            null 
    ,domestic_ultimate_state_province_abbreviation          text                null 
    ,global_ultimate_indicator                              char                null 
    ,global_ultimate_iso_country_code                       char(2)             null 
    ,global_ultimate_fips_country_region_code               int                 null 
    ,global_ultimate_db_country_region_code                 smallint            null 
    ,global_ultimate_state_province_abbreviation            text                null 
    ,headquarter_duns_number                                bigint              null 
    ,headquarter_parent_business_name                       text                null 
    ,headquarters_iso_country_code                          char(2)             null 
    ,headquarter_parent_db_country_region_code              text                null 
    ,headquarter_parent_fips_country_region_code            int                 null 
    ,headquarter_parent_state_province                      text                null 
    ,major_industry_category                                smallint            null 
    ,major_industry_category_name                           text                null 
    ,related_industries                                     text                null 
    ,line_of_business                                       text                null 
    ,us_1987_sic_1                                          int                 null 
    ,us_1987_sic_2                                          int                 null 
    ,us_1987_sic_3                                          int                 null 
    ,us_1987_sic_4                                          int                 null 
    ,us_1987_sic_5                                          int                 null 
    ,us_1987_sic_6                                          int                 null 
    ,primary_naics_1_1                                      int                 null 
    ,primary_naics_1_2                                      int                 null 
    ,primary_naics_1_3                                      int                 null 
    ,primary_naics_1_4                                      int                 null 
    ,naics_2_1_code                                         int                 null 
    ,naics_2_2_code                                         int                 null 
    ,naics_2_3_code                                         int                 null 
    ,naics_2_4_code                                         int                 null 
    ,naics_3_1_code                                         int                 null 
    ,naics_3_2_code                                         int                 null 
    ,naics_3_3_code                                         int                 null 
    ,naics_3_4_code                                         int                 null 
    ,naics_4_1_code                                         int                 null 
    ,naics_4_2_code                                         int                 null 
    ,naics_4_3_code                                         int                 null 
    ,naics_4_4_code                                         int                 null 
    ,naics_5_1_code                                         int                 null 
    ,naics_5_2_code                                         int                 null 
    ,naics_5_3_code                                         int                 null 
    ,naics_5_4_code                                         int                 null 
    ,naics_6_1_code                                         int                 null 
    ,naics_6_2_code                                         int                 null 
    ,naics_6_3_code                                         int                 null 
    ,naics_6_4_code                                         int                 null 
    ,uk_sic_2007                                            int                 null 
    ,chief_executive_officer_name                           text                null 
    ,chief_executive_officer_first_name                     text                null 
    ,chief_executive_officer_middle_initial                 text                null 
    ,chief_executive_officer_last_name                      text                null 
    ,chief_executive_officer_suffix                         text                null 
    ,chief_executive_officer_prefix                         text                null 
    ,chief_executive_officer_title                          text                null 
    ,first_executive_first_name                             text                null 
    ,first_executive_middle_initial                         text                null 
    ,first_executive_last_name                              text                null 
    ,first_executive_suffix                                 text                null 
    ,first_executive_prefix                                 text                null 
    ,first_executive_title                                  text                null 
    ,first_executive_mrc_code                               text                null 
    ,second_executive_first_name                            text                null 
    ,second_executive_middle_initial                        text                null 
    ,second_executive_last_name                             text                null 
    ,second_executive_suffix                                text                null 
    ,second_executive_prefix                                text                null 
    ,second_executive_title                                 text                null 
    ,second_executive_mrc_code                              text                null 
    ,third_executive_first_name                             text                null 
    ,third_executive_middle_initial                         text                null 
    ,third_executive_last_name                              text                null 
    ,third_executive_suffix                                 text                null 
    ,third_executive_prefix                                 text                null 
    ,third_executive_title                                  text                null 
    ,third_executive_mrc_code                               text                null 
    ,ceo_mgmt_responsibility_code                           text                null 
    ,chief_executive_officer_gender_code                    char                null 
    ,source_file                                            text                null 
    ,constraint db_optimizer_pkey   primary key (duns_number)
);
go 

/*** PERMISSIONS ***/
alter table public.db_optimizer owner to mj_admin;
go 

grant select on public.db_optimizer to rl_public_r;
go 

grant insert on public.db_optimizer to rl_public_a;
go 

grant update on public.db_optimizer to rl_public_w;
go 
