DROP TABLE IF EXISTS public.iso_state_province CASCADE;
GO 

CREATE TABLE public.iso_state_province (
	 iso_2 				char(2) 	NULL 
	,state_province 	TEXT 		NULL 
	,country_id 		int 		NOT NULL
	,id 				bigint 		NOT NULL 	GENERATED BY DEFAULT AS IDENTITY
	,CONSTRAINT iso_state_province_pkey PRIMARY KEY (id)
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE public.iso_state_province OWNER TO mj_admin;
GO 

GRANT SELECT ON TABLE public.iso_state_province TO rl_public_r;
GO 
