DROP TABLE IF EXISTS public.iso_country CASCADE;
GO 

CREATE TABLE public.iso_country (
	 iso_2 			char(2) 	NULL 
	,country_name 	TEXT 		NOT NULL 
	,iso_3 			char(3) 	NULL 
	,id 			bigint 		NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 
	,CONSTRAINT iso_country_pkey PRIMARY KEY (id)
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE public.iso_country OWNER TO mj_admin;
GO 

GRANT SELECT ON TABLE public.iso_country TO rl_public_r;
GO 
