create or replace function benefitpoint.tr_audit_product_u() 
returns trigger 
language plpgsql 
as $$

begin 
    insert into benefitpoint.audit_product(
         product_id 
        ,account_id 
        ,old_product_type_id 
        ,new_product_type_id 
        ,old_is_additional_product 
        ,new_is_additional_product 
        ,old_product_status 
        ,new_product_status 
        ,old_name 
        ,new_name 
        ,old_carrier_id 
        ,new_carrier_id 
        ,old_broker_of_record_account_id 
        ,new_broker_of_record_account_id 
        ,old_broker_of_record_as_of 
        ,new_broker_of_record_as_of 
        ,old_policy_number 
        ,new_policy_number 
        ,old_policy_origination_reason 
        ,new_policy_origination_reason 
        ,old_policy_origination_reason_qualifier_id 
        ,new_policy_origination_reason_qualifier_id 
        ,old_parent_product_id 
        ,new_parent_product_id 
        ,old_effective_as_of 
        ,new_effective_as_of 
        ,old_renewal_on 
        ,new_renewal_on 
        ,old_continuous_policy 
        ,new_continuous_policy 
        ,old_original_effective_as_of 
        ,new_original_effective_as_of 
        ,old_cancellation_on 
        ,new_cancellation_on 
        ,old_cancellation_reason 
        ,new_cancellation_reason 
        ,old_cancellation_additional_information 
        ,new_cancellation_additional_information 
        ,old_reinstatement_on 
        ,new_reinstatement_on 
        ,old_reinstatement_reason 
        ,new_reinstatement_reason 
        ,old_reinstatement_additional_information 
        ,new_reinstatement_additional_information 
        ,old_voluntary_product 
        ,new_voluntary_product 
        ,old_union_product 
        ,new_union_product 
        ,old_non_payable 
        ,new_non_payable 
        ,old_non_revenue 
        ,new_non_revenue 
        ,old_premium_payment_frequency 
        ,new_premium_payment_frequency 
        ,old_number_of_eligible_employees 
        ,new_number_of_eligible_employees 
        ,old_total_estimated_monthly_revenue 
        ,new_total_estimated_monthly_revenue 
        ,old_total_estimated_monthly_premium 
        ,new_total_estimated_monthly_premium 
        ,old_billing_type 
        ,new_billing_type 
        ,old_billing_carrier_type 
        ,new_billing_carrier_type 
        ,old_billing_carrier_id 
        ,new_billing_carrier_id 
        ,old_office_id 
        ,new_office_id 
        ,old_department_id 
        ,new_department_id 
        ,old_primary_sales_lead_user_id 
        ,new_primary_sales_lead_user_id 
        ,old_primary_servicer_lead_user_id 
        ,new_primary_servicer_lead_user_id 
        ,old_last_modified_on 
        ,new_last_modified_on 
        ,old_created_on 
        ,new_created_on 
        ,old_metal_level_type 
        ,new_metal_level_type 
        ,old_aca_safe_harbor_type 
        ,new_aca_safe_harbor_type 
        ,old_aca_sage_harbor_reporting_year 
        ,new_aca_sage_harbor_reporting_year 
        ,old_custom_cancellation_reason_id 
        ,new_custom_cancellation_reason_id 
        ,audit_action 
    )
    select   old.product_id 
            ,old.account_id 
            ,old.product_type_id 
            ,new.product_type_id 
            ,old.is_additional_product 
            ,new.is_additional_product 
            ,old.product_status 
            ,new.product_status 
            ,old.name 
            ,new.name 
            ,old.carrier_id 
            ,new.carrier_id 
            ,old.broker_of_record_account_id 
            ,new.broker_of_record_account_id 
            ,old.broker_of_record_as_of 
            ,new.broker_of_record_as_of 
            ,old.policy_number 
            ,new.policy_number 
            ,old.policy_origination_reason 
            ,new.policy_origination_reason 
            ,old.policy_origination_reason_qualifier_id 
            ,new.policy_origination_reason_qualifier_id 
            ,old.parent_product_id 
            ,new.parent_product_id 
            ,old.effective_as_of 
            ,new.effective_as_of 
            ,old.renewal_on 
            ,new.renewal_on 
            ,old.continuous_policy 
            ,new.continuous_policy 
            ,old.original_effective_as_of 
            ,new.original_effective_as_of 
            ,old.cancellation_on 
            ,new.cancellation_on 
            ,old.cancellation_reason 
            ,new.cancellation_reason 
            ,old.cancellation_additional_information 
            ,new.cancellation_additional_information 
            ,old.reinstatement_on 
            ,new.reinstatement_on 
            ,old.reinstatement_reason 
            ,new.reinstatement_reason 
            ,old.reinstatement_additional_information 
            ,new.reinstatement_additional_information 
            ,old.voluntary_product 
            ,new.voluntary_product 
            ,old.union_product 
            ,new.union_product 
            ,old.non_payable 
            ,new.non_payable 
            ,old.non_revenue 
            ,new.non_revenue 
            ,old.premium_payment_frequency 
            ,new.premium_payment_frequency 
            ,old.number_of_eligible_employees 
            ,new.number_of_eligible_employees 
            ,old.total_estimated_monthly_revenue 
            ,new.total_estimated_monthly_revenue 
            ,old.total_estimated_monthly_premium 
            ,new.total_estimated_monthly_premium 
            ,old.billing_type 
            ,new.billing_type 
            ,old.billing_carrier_type 
            ,new.billing_carrier_type 
            ,old.billing_carrier_id 
            ,new.billing_carrier_id 
            ,old.office_id 
            ,new.office_id 
            ,old.department_id 
            ,new.department_id 
            ,old.primary_sales_lead_user_id 
            ,new.primary_sales_lead_user_id 
            ,old.primary_servicer_lead_user_id 
            ,new.primary_servicer_lead_user_id 
            ,old.last_modified_on 
            ,new.last_modified_on 
            ,old.created_on 
            ,new.created_on 
            ,old.metal_level_type 
            ,new.metal_level_type 
            ,old.aca_safe_harbor_type 
            ,new.aca_safe_harbor_type 
            ,old.aca_sage_harbor_reporting_year 
            ,new.aca_sage_harbor_reporting_year 
            ,old.custom_cancellation_reason_id 
            ,new.custom_cancellation_reason_id 
            ,'U'; 
    return old;
end;
$$;
go 

/*** PERMISSIONS ***/
alter function benefitpoint.tr_audit_product_u() owner to mj_admin;
go 

grant execute on function benefitpoint.tr_audit_product_u() to rl_benefitpoint_x;
go 