CREATE FUNCTION powerapps.tr_audit_prospect_u()
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$

BEGIN 
	INSERT INTO powerapps.audit_prospect(
		 old_propsect_name 
		,new_propsect_name 
		,old_account_name 
		,new_account_name 
		,old_line_of_business 
		,new_line_of_business 
		,old_department 
		,new_department 
		,old_primary_contact 
		,new_primary_contact 
		,old_est_revenue 
		,new_est_revenue 
		,old_last_activity_date 
		,new_last_activity_date 
		,old_nbr_of_activities 
		,new_nbr_of_activities 
		,old_nbr_of_activities_last_90 
		,new_nbr_of_activities_last_90 
		,old_prospect_401k 
		,new_prospect_401k 
		,old_active_producer 
		,new_active_producer 
		,old_aor_effective_date 
		,new_aor_effective_date 
		,old_carrier 
		,new_carrier 
		,old_client_category 
		,new_client_category 
		,old_client_onboarding_initiated 
		,new_client_onboarding_initiated 
		,old_close_prospect_as_lost 
		,new_close_prospect_as_lost 
		,old_close_prospect_as_won 
		,new_close_prospect_as_won 
		,old_committed_revenue 
		,new_committed_revenue 
		,old_company_estimated_annual_revenue 
		,new_company_estimated_annual_revenue 
		,old_cpa_firm 
		,new_cpa_firm 
		,old_current_broker 
		,new_current_broker 
		,old_current_lost_notes 
		,new_current_lost_notes 
		,old_current_mj_client 
		,new_current_mj_client 
		,old_current_reason_for_lost 
		,new_current_reason_for_lost 
		,old_date_of_first_meeting 
		,new_date_of_first_meeting 
		,old_date_of_proposal_meeting 
		,new_date_of_proposal_meeting 
		,old_estimated_annual_payroll 
		,new_estimated_annual_payroll 
		,old_expected_decision_date 
		,new_expected_decision_date 
		,old_first_meeting_completed 
		,new_first_meeting_completed 
		,old_former_mj_client 
		,new_former_mj_client 
		,old_funding_type 
		,new_funding_type 
		,old_japanese_owned_business 
		,new_japanese_owned_business 
		,old_marketing_account_type 
		,new_marketing_account_type 
		,old_marketing_industry_segment 
		,new_marketing_industry_segment 
		,old_marketing_lifecycle_stage 
		,new_marketing_lifecycle_stage 
		,old_mentor 
		,new_mentor 
		,old_mentor_assigned 
		,new_mentor_assigned 
		,old_number_of_employees 
		,new_number_of_employees 
		,old_number_of_locations 
		,new_number_of_locations 
		,old_ongoing_discussion 
		,new_ongoing_discussion 
		,old_payroll_or_hris_provider 
		,new_payroll_or_hris_provider 
		,old_primary_competitor_for_lost_prospect 
		,new_primary_competitor_for_lost_prospect 
		,old_producer_1 
		,new_producer_1 
		,old_producer_2 
		,new_producer_2 
		,old_producer_3 
		,new_producer_3 
		,old_producer_split 				
		,new_producer_split 				
		,old_proposal_meeting_completed 
		,new_proposal_meeting_completed 
		,old_prospect_bpf_finished 
		,new_prospect_bpf_finished 
		,old_propsect_decision 
		,new_propsect_decision 
		,old_qualified_revenue 
		,new_qualified_revenue 
		,old_recurring_revenue 
		,new_recurring_revenue 
		,old_renewal_date 
		,new_renewal_date 
		,old_request_for_proposal 
		,new_request_for_proposal 
		,old_revenue_effective_date 
		,new_revenue_effective_date 
		,old_scheduled_first_meeting 
		,new_scheduled_first_meeting 
		,old_scheduled_proposal_meeting 
		,new_scheduled_proposal_meeting 
		,old_county 
		,new_county 
		,old_premium_volume 
		,new_premium_volume 
		,old_ex_mod 
		,new_ex_mod 
		,old_estimated_annual_premium 
		,new_estimated_annual_premium 
		,old_drivers 
		,new_drivers 
		,old_vehicles 
		,new_vehicles 
		,old_mileage 
		,new_mileage 
		,old_fiedlity_bond 
		,new_fiedlity_bond 
		,old_pc_self_funded 
		,new_pc_self_funded 
		,old_cargo_carrier 
		,new_cargo_carrier 
		,old_cargo_renewal 
		,new_cargo_renewal 
		,old_business_travel_carrier 
		,new_business_travel_carrier 
		,old_business_travel_renewal 
		,new_business_travel_renewal 
		,old_miedge_industry 
		,new_miedge_industry 
		,old_actuary_firm_name 
		,new_actuary_firm_name 
		,old_actuary_contact_name 
		,new_actuary_contact_name 
		,old_prospect_owner 
		,new_prospect_owner 
		,old_created_on 
		,new_created_on 
		,old_created_by 
		,new_created_by 
		,old_modified_on 
		,new_modified_on 
		,old_modified_by 
		,new_modified_by 
		,old_status 
		,new_status 
		,old_status_reason 
		,new_status_reason 
		,old_prospect_source 
		,new_prospect_source 
		,old_source_key 
		,new_source_key 
		,guid 
		,audit_action 
	)
	SELECT 	 OLD.propsect_name 
			,NEW.propsect_name 
			,OLD.account_name 
			,NEW.account_name 
			,OLD.line_of_business 
			,NEW.line_of_business 
			,OLD.department 
			,NEW.department 
			,OLD.primary_contact 
			,NEW.primary_contact 
			,OLD.est_revenue 
			,NEW.est_revenue 
			,OLD.last_activity_date 
			,NEW.last_activity_date 
			,OLD.nbr_of_activities 
			,NEW.nbr_of_activities 
			,OLD.nbr_of_activities_last_90 
			,NEW.nbr_of_activities_last_90 
			,OLD.prospect_401k 
			,NEW.prospect_401k 
			,OLD.active_producer 
			,NEW.active_producer 
			,OLD.aor_effective_date 
			,NEW.aor_effective_date 
			,OLD.carrier 
			,NEW.carrier 
			,OLD.client_category 
			,NEW.client_category 
			,OLD.client_onboarding_initiated 
			,NEW.client_onboarding_initiated 
			,OLD.close_prospect_as_lost 
			,NEW.close_prospect_as_lost 
			,OLD.close_prospect_as_won 
			,NEW.close_prospect_as_won 
			,OLD.committed_revenue 
			,NEW.committed_revenue 
			,OLD.company_estimated_annual_revenue 
			,NEW.company_estimated_annual_revenue 
			,OLD.cpa_firm 
			,NEW.cpa_firm 
			,OLD.current_broker 
			,NEW.current_broker 
			,OLD.current_lost_notes 
			,NEW.current_lost_notes 
			,OLD.current_mj_client 
			,NEW.current_mj_client 
			,OLD.current_reason_for_lost 
			,NEW.current_reason_for_lost 
			,OLD.date_of_first_meeting 
			,NEW.date_of_first_meeting 
			,OLD.date_of_proposal_meeting 
			,NEW.date_of_proposal_meeting 
			,OLD.estimated_annual_payroll 
			,NEW.estimated_annual_payroll 
			,OLD.expected_decision_date 
			,NEW.expected_decision_date 
			,OLD.first_meeting_completed 
			,NEW.first_meeting_completed 
			,OLD.former_mj_client 
			,NEW.former_mj_client 
			,OLD.funding_type 
			,NEW.funding_type 
			,OLD.japanese_owned_business 
			,NEW.japanese_owned_business 
			,OLD.marketing_account_type 
			,NEW.marketing_account_type 
			,OLD.marketing_industry_segment 
			,NEW.marketing_industry_segment 
			,OLD.marketing_lifecycle_stage 
			,NEW.marketing_lifecycle_stage 
			,OLD.mentor 
			,NEW.mentor 
			,OLD.mentor_assigned 
			,NEW.mentor_assigned 
			,OLD.number_of_employees 
			,NEW.number_of_employees 
			,OLD.number_of_locations 
			,NEW.number_of_locations 
			,OLD.ongoing_discussion 
			,NEW.ongoing_discussion 
			,OLD.payroll_or_hris_provider 
			,NEW.payroll_or_hris_provider 
			,OLD.primary_competitor_for_lost_prospect 
			,NEW.primary_competitor_for_lost_prospect 
			,OLD.producer_1 
			,NEW.producer_1 
			,OLD.producer_2 
			,NEW.producer_2 
			,OLD.producer_3 
			,NEW.producer_3 
			,OLD.producer_split 				
			,NEW.producer_split 				
			,OLD.proposal_meeting_completed 
			,NEW.proposal_meeting_completed 
			,OLD.prospect_bpf_finished 
			,NEW.prospect_bpf_finished 
			,OLD.propsect_decision 
			,NEW.propsect_decision 
			,OLD.qualified_revenue 
			,NEW.qualified_revenue 
			,OLD.recurring_revenue 
			,NEW.recurring_revenue 
			,OLD.renewal_date 
			,NEW.renewal_date 
			,OLD.request_for_proposal 
			,NEW.request_for_proposal 
			,OLD.revenue_effective_date 
			,NEW.revenue_effective_date 
			,OLD.scheduled_first_meeting 
			,NEW.scheduled_first_meeting 
			,OLD.scheduled_proposal_meeting 
			,NEW.scheduled_proposal_meeting 
			,OLD.county 
			,NEW.county 
			,OLD.premium_volume 
			,NEW.premium_volume 
			,OLD.ex_mod 
			,NEW.ex_mod 
			,OLD.estimated_annual_premium 
			,NEW.estimated_annual_premium 
			,OLD.drivers 
			,NEW.drivers 
			,OLD.vehicles 
			,NEW.vehicles 
			,OLD.mileage 
			,NEW.mileage 
			,OLD.fiedlity_bond 
			,NEW.fiedlity_bond 
			,OLD.pc_self_funded 
			,NEW.pc_self_funded 
			,OLD.cargo_carrier 
			,NEW.cargo_carrier 
			,OLD.cargo_renewal 
			,NEW.cargo_renewal 
			,OLD.business_travel_carrier 
			,NEW.business_travel_carrier 
			,OLD.business_travel_renewal 
			,NEW.business_travel_renewal 
			,OLD.miedge_industry 
			,NEW.miedge_industry 
			,OLD.actuary_firm_name 
			,NEW.actuary_firm_name 
			,OLD.actuary_contact_name 
			,NEW.actuary_contact_name 
			,OLD.prospect_owner 
			,NEW.prospect_owner 
			,OLD.created_on 
			,NEW.created_on 
			,OLD.created_by 
			,NEW.created_by 
			,OLD.modified_on 
			,NEW.modified_on 
			,OLD.modified_by 
			,NEW.modified_by 
			,OLD.status 
			,NEW.status 
			,OLD.status_reason 
			,NEW.status_reason 
			,OLD.prospect_source 
			,NEW.prospect_source 
			,OLD.source_key 
			,NEW.source_key 
			,OLD.guid 
			,'U';
	RETURN OLD;
END;
$$;
GO 

/*** PERMISSIONS ***/
ALTER FUNCTION powerapps.tr_audit_prospect_u() OWNER TO mj_admin;
GO 
GRANT EXECUTE ON FUNCTION powerapps.tr_audit_prospect_u() TO rl_powerapps_x;
GO 
