CREATE FUNCTION powerapps.tr_audit_prospect_i()
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$

BEGIN 
	INSERT INTO powerapps.audit_prospect(
		 new_propsect_name 
		,new_account_name 
		,new_line_of_business 
		,new_department 
		,new_primary_contact 
		,new_est_revenue 
		,new_last_activity_date 
		,new_nbr_of_activities 
		,new_nbr_of_activities_last_90 
		,new_prospect_401k 
		,new_active_producer 
		,new_aor_effective_date 
		,new_carrier 
		,new_client_category 
		,new_client_onboarding_initiated 
		,new_close_prospect_as_lost 
		,new_close_prospect_as_won 
		,new_committed_revenue 
		,new_company_estimated_annual_revenue 
		,new_cpa_firm 
		,new_current_broker 
		,new_current_lost_notes 
		,new_current_mj_client 
		,new_current_reason_for_lost 
		,new_date_of_first_meeting 
		,new_date_of_proposal_meeting 
		,new_estimated_annual_payroll 
		,new_expected_decision_date 
		,new_first_meeting_completed 
		,new_former_mj_client 
		,new_funding_type 
		,new_japanese_owned_business 
		,new_marketing_account_type 
		,new_marketing_industry_segment 
		,new_marketing_lifecycle_stage 
		,new_mentor 
		,new_mentor_assigned 
		,new_number_of_employees 
		,new_number_of_locations 
		,new_ongoing_discussion 
		,new_payroll_or_hris_provider 
		,new_primary_competitor_for_lost_prospect 
		,new_producer_1 
		,new_producer_2 
		,new_producer_3 
		,new_producer_split 				
		,new_proposal_meeting_completed 
		,new_prospect_bpf_finished 
		,new_propsect_decision 
		,new_qualified_revenue 
		,new_recurring_revenue 
		,new_renewal_date 
		,new_request_for_proposal 
		,new_revenue_effective_date 
		,new_scheduled_first_meeting 
		,new_scheduled_proposal_meeting 
		,new_county 
		,new_premium_volume 
		,new_ex_mod 
		,new_estimated_annual_premium 
		,new_drivers 
		,new_vehicles 
		,new_mileage 
		,new_fiedlity_bond 
		,new_pc_self_funded 
		,new_cargo_carrier 
		,new_cargo_renewal 
		,new_business_travel_carrier 
		,new_business_travel_renewal 
		,new_miedge_industry 
		,new_actuary_firm_name 
		,new_actuary_contact_name 
		,new_prospect_owner 
		,new_created_on 
		,new_created_by 
		,new_modified_on 
		,new_modified_by 
		,new_status 
		,new_status_reason 
		,new_prospect_source 
		,new_source_key 
		,guid 
		,audit_action 
	)
	SELECT 	 NEW.propsect_name 
			,NEW.account_name 
			,NEW.line_of_business 
			,NEW.department 
			,NEW.primary_contact 
			,NEW.est_revenue 
			,NEW.last_activity_date 
			,NEW.nbr_of_activities 
			,NEW.nbr_of_activities_last_90 
			,NEW.prospect_401k 
			,NEW.active_producer 
			,NEW.aor_effective_date 
			,NEW.carrier 
			,NEW.client_category 
			,NEW.client_onboarding_initiated 
			,NEW.close_prospect_as_lost 
			,NEW.close_prospect_as_won 
			,NEW.committed_revenue 
			,NEW.company_estimated_annual_revenue 
			,NEW.cpa_firm 
			,NEW.current_broker 
			,NEW.current_lost_notes 
			,NEW.current_mj_client 
			,NEW.current_reason_for_lost 
			,NEW.date_of_first_meeting 
			,NEW.date_of_proposal_meeting 
			,NEW.estimated_annual_payroll 
			,NEW.expected_decision_date 
			,NEW.first_meeting_completed 
			,NEW.former_mj_client 
			,NEW.funding_type 
			,NEW.japanese_owned_business 
			,NEW.marketing_account_type 
			,NEW.marketing_industry_segment 
			,NEW.marketing_lifecycle_stage 
			,NEW.mentor 
			,NEW.mentor_assigned 
			,NEW.number_of_employees 
			,NEW.number_of_locations 
			,NEW.ongoing_discussion 
			,NEW.payroll_or_hris_provider 
			,NEW.primary_competitor_for_lost_prospect 
			,NEW.producer_1 
			,NEW.producer_2 
			,NEW.producer_3 
			,NEW.producer_split 				
			,NEW.proposal_meeting_completed 
			,NEW.prospect_bpf_finished 
			,NEW.propsect_decision 
			,NEW.qualified_revenue 
			,NEW.recurring_revenue 
			,NEW.renewal_date 
			,NEW.request_for_proposal 
			,NEW.revenue_effective_date 
			,NEW.scheduled_first_meeting 
			,NEW.scheduled_proposal_meeting 
			,NEW.county 
			,NEW.premium_volume 
			,NEW.ex_mod 
			,NEW.estimated_annual_premium 
			,NEW.drivers 
			,NEW.vehicles 
			,NEW.mileage 
			,NEW.fiedlity_bond 
			,NEW.pc_self_funded 
			,NEW.cargo_carrier 
			,NEW.cargo_renewal 
			,NEW.business_travel_carrier 
			,NEW.business_travel_renewal 
			,NEW.miedge_industry 
			,NEW.actuary_firm_name 
			,NEW.actuary_contact_name 
			,NEW.prospect_owner 
			,NEW.created_on 
			,NEW.created_by 
			,NEW.modified_on 
			,NEW.modified_by 
			,NEW.status 
			,NEW.status_reason 
			,NEW.prospect_source 
			,NEW.source_key 
			,NEW.guid 
			,'I';
	RETURN NEW;
END;
$$;
GO 

/*** PERMISSIONS ***/
ALTER FUNCTION powerapps.tr_audit_prospect_i() OWNER TO mj_admin;
GO 
GRANT EXECUTE ON FUNCTION powerapps.tr_audit_prospect_i() TO rl_powerapps_x;
GO 
