DROP TABLE IF EXISTS config.benefitpoint_file_import;

CREATE TABLE config.benefitpoint_file_import (
	 entity 		TEXT 		NULL 
	,file 			TEXT 		NULL 
	,file_cols 		TEXT 		NULL 
	,target 		TEXT 		NULL 
	,target_cols 	TEXT 		NULL 
	,merge_col 		TEXT 		NULL 
	,proc_ord 		smallint 	null
	,active 		bool 		NOT NULL 	DEFAULT FALSE 
	,id 			bigint 		NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
	,modify_dt 		timestamp 	NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,modify_user 	TEXT 		NOT NULL 	DEFAULT current_user
);

ALTER TABLE config.benefitpoint_file_import OWNER TO postgres_dev;