DROP TABLE IF EXISTS p_and_c.mapping_coverage_types CASCADE;
GO

CREATE TABLE p_and_c.mapping_coverage_types (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	carrier_coverage_type text NOT NULL,
	loss_type_id int4 NULL,
	CONSTRAINT mapping_coverage_types_ukey UNIQUE (carrier_coverage_type)
);
GO

/*** PERMISSIONS ***/
ALTER TABLE p_and_c.mapping_coverage_types OWNER TO mj_admin;
GO

Grant update, insert, select on table p_and_c.mapping_coverage_types to rl_pc_data_analyst;
GO

Grant select on table p_and_c.mapping_coverage_types to rl_pc_rpa_developer;
GO

Grant select on table p_and_c.mapping_coverage_types to rpauser;
GO
GRANT SELECT ON p_and_c.mapping_coverage_types to rl_p_and_c_r;
GO

GRANT INSERT ON p_and_c.mapping_coverage_types to rl_p_and_c_a;
GO

GRANT UPDATE ON p_and_c.mapping_coverage_types to rl_p_and_c_w;
GO

GRANT DELETE ON p_and_c.mapping_coverage_types to rl_p_and_c_d;
GO