CREATE TABLE p_and_c.raw_sencc_wc (
	"Policy Year" varchar(256) NULL,
	"Loc Code" varchar(256) NULL,
	"Dept Code" varchar(256) NULL,
	"Loss Date" varchar(256) NULL,
	"Claim #" varchar(256) NULL,
	"Claimant Name" varchar(256) NULL,
	"Claimant Status" varchar(256) NULL,
	"Claim Type" varchar(256) NULL,
	"Part WC" varchar(256) NULL,
	"Nature WC" varchar(256) NULL,
	"Cause WC" varchar(256) NULL,
	"Accident State" varchar(256) NULL,
	"Employer Lag Days" varchar(256) NULL,
	"Sentry Lag Days" varchar(256) NULL,
	"Total Lag Days" varchar(256) NULL,
	"Age at Injury" varchar(256) NULL,
	"Current Age" varchar(256) NULL,
	"Benefit State" varchar(256) NULL,
	"Hire Date" varchar(256) NULL,
	"Close Date" varchar(256) NULL,
	"Claim Status" varchar(256) NULL,
	"Adjuster #" varchar(256) NULL,
	"Adjuster Name" varchar(256) NULL,
	"Medical Status" varchar(256) NULL,
	"Medical Paid Loss" varchar(256) NULL,
	"Medical Paid Expense" varchar(256) NULL,
	"Medical Reserve" varchar(256) NULL,
	"Medical Incurred" varchar(256) NULL,
	"Indemnity Status" varchar(256) NULL,
	"Indemnity Paid Loss" varchar(256) NULL,
	"Indemnity Paid Expense" varchar(256) NULL,
	"Indemnity Reserve" varchar(256) NULL,
	"Indemnity Incurred" varchar(256) NULL,
	"Incurred" varchar(256) NULL,
	"Claim Count" varchar(256) NULL,
	"Account #" varchar(256) NULL,
	"Cause Code WC" varchar(256) NULL,
	"Claim Complexity" varchar(256) NULL,
	"Class Code" varchar(256) NULL,
	"Closed Claim Count" varchar(256) NULL,
	"Compensation Rate" varchar(256) NULL,
	"Date Reported to Sentry" varchar(256) NULL,
	"Denial Date" varchar(256) NULL,
	"Denial Status" varchar(256) NULL,
	"Dept Description" varchar(256) NULL,
	"Dept Name" varchar(256) NULL,
	"Description" varchar(4096) NULL,
	"Employment Status" varchar(256) NULL,
	"Expense Est" varchar(256) NULL,
	"First Name" varchar(256) NULL,
	"Foreign Claim #" varchar(256) NULL,
	"Gender" varchar(256) NULL,
	"Incurred incl TPA" varchar(256) NULL,
	"Incurred Minus Paid Expense" varchar(256) NULL,
	"Incurred Over Deductible Limit" varchar(256) NULL,
	"Incurred Within Deductible Limit" varchar(256) NULL,
	"Indemnity Claim Count" varchar(256) NULL,
	"Indemnity Incurred Minus Paid Expense" varchar(256) NULL,
	"Indemnity Paid Loss Expense" varchar(256) NULL,
	"Indemnity Paid Over Deductible Limit" varchar(256) NULL,
	"Indemnity Paid Within Deductible Limit" varchar(256) NULL,
	"Injury Cause Category" varchar(256) NULL,
	"Last Name" varchar(256) NULL,
	"Line of Business" varchar(256) NULL,
	"Litigated Claim Count" varchar(256) NULL,
	"Litigation Status" varchar(256) NULL,
	"Loc Description" varchar(256) NULL,
	"Loc Name" varchar(256) NULL,
	"Location City" varchar(256) NULL,
	"Location State" varchar(256) NULL,
	"Loss Date Calendar Year" varchar(256) NULL,
	"Loss Date Fiscal Year" varchar(256) NULL,
	"Loss Day of Week" varchar(256) NULL,
	"Medical Claim Count" varchar(256) NULL,
	"Medical Incurred Minus Paid Expense" varchar(256) NULL,
	"Medical Paid Loss Expense" varchar(256) NULL,
	"Medical Paid Over Deductible Limit" varchar(256) NULL,
	"Medical Paid Within Deductible Limit" varchar(256) NULL,
	"MTD Incurred" varchar(256) NULL,
	"MTD Indemnity Incurred" varchar(256) NULL,
	"MTD Indemnity Paid Expense" varchar(256) NULL,
	"MTD Indemnity Paid Loss" varchar(256) NULL,
	"MTD Indemnity Paid Loss Expense" varchar(256) NULL,
	"MTD Indemnity Reserve" varchar(256) NULL,
	"MTD Medical Incurred" varchar(256) NULL,
	"MTD Medical Paid Expense" varchar(256) NULL,
	"MTD Medical Paid Loss" varchar(256) NULL,
	"MTD Medical Paid Loss Expense" varchar(256) NULL,
	"MTD Medical Reserve" varchar(256) NULL,
	"MTD Paid Expense" varchar(256) NULL,
	"MTD Paid Loss" varchar(256) NULL,
	"MTD Paid Loss Expense" varchar(256) NULL,
	"MTD Reserve" varchar(256) NULL,
	"Nature Code WC" varchar(256) NULL,
	"Nature of Accident Category" varchar(256) NULL,
	"Occupation" varchar(256) NULL,
	"Open Claim Count" varchar(256) NULL,
	"Paid Expense" varchar(256) NULL,
	"Paid Expense incl TPA" varchar(256) NULL,
	"Paid Expense Over Deductible Limit" varchar(256) NULL,
	"Paid Expense Within Deductible Limit" varchar(256) NULL,
	"Paid Loss" varchar(256) NULL,
	"Paid Loss Expense" varchar(256) NULL,
	"Paid Loss Expense incl TPA" varchar(256) NULL,
	"Paid Loss Expense Over Deductible Limit" varchar(256) NULL,
	"Paid Loss Expense Within Deductible Limit" varchar(256) NULL,
	"Paid Loss Incl TPA" varchar(256) NULL,
	"Paid Loss Over Deductible Limit" varchar(256) NULL,
	"Paid Loss Within Deductible Limit" varchar(256) NULL,
	"Part Code WC" varchar(256) NULL,
	"Part of Body Category" varchar(256) NULL,
	"Patient Handling" varchar(256) NULL,
	"Policy #" varchar(256) NULL,
	"Policy Description" varchar(256) NULL,
	"Policy Effective Date" varchar(256) NULL,
	"Policy Expiration Date" varchar(256) NULL,
	"Policy Full #" varchar(256) NULL,
	"Policy Suffix" varchar(256) NULL,
	"Rate State" varchar(256) NULL,
	"Record Only" varchar(256) NULL,
	"Record Only Claim Count" varchar(256) NULL,
	"Reopen Date" varchar(256) NULL,
	"Reserve" varchar(256) NULL,
	"Set Up Date" varchar(256) NULL,
	"SIC Code" varchar(256) NULL,
	"Subrogation Recovery" varchar(256) NULL,
	"Subrogation Status" varchar(256) NULL,
	"Suit Closed Date" varchar(256) NULL,
	"Suit Open Date" varchar(256) NULL,
	"Suit Reopen Date" varchar(256) NULL,
	"Time of Day" varchar(256) NULL,
	"TPA Indemnity Paid Expense" varchar(256) NULL,
	"TPA Indemnity Paid Loss" varchar(256) NULL,
	"TPA Medical Paid Expense" varchar(256) NULL,
	"TPA Medical Paid Loss" varchar(256) NULL,
	"TPA Paid Expense" varchar(256) NULL,
	"TPA Paid Loss" varchar(256) NULL,
	"Weekly Wage Amount" varchar(256) NULL,
	filename varchar(256) NULL,
	uploaded_at varchar(256) NULL,
	"Legacy Policy #" varchar(256) NULL,
	"Litigation Status Detail" varchar(256) NULL
);
GO

/*** PERMISSIONS ***/
ALTER TABLE p_and_c.raw_sencc_wc OWNER TO mj_admin;
GO

Grant select on table p_and_c.raw_sencc_wc to rl_pc_data_analyst;
GO

Grant select on table p_and_c.raw_sencc_wc to rl_pc_rpa_developer;
GO

Grant delete, update, insert, select on table p_and_c.raw_sencc_wc to rpauser;
GO
GRANT SELECT ON p_and_c.raw_sencc_wc to rl_p_and_c_r;
GO

GRANT INSERT ON p_and_c.raw_sencc_wc to rl_p_and_c_a;
GO

GRANT UPDATE ON p_and_c.raw_sencc_wc to rl_p_and_c_w;
GO

GRANT DELETE ON p_and_c.raw_sencc_wc to rl_p_and_c_d;
GO