create or replace function sagitta.tr_audit_payees_u() 
returns trigger 
language plpgsql 
as $$ 

begin 
    insert into sagitta.audit_payees (
         sagitem 
        ,old_audit_staff_cd
        ,new_audit_staff_cd
        ,old_audit_entry_dt
        ,new_audit_entry_dt
        ,old_audit_time
        ,new_audit_time
        ,old_audit_cd
        ,new_audit_cd
        ,old_audit_history_record_number
        ,new_audit_history_record_number
        ,old_audit_program
        ,new_audit_program
        ,old_audit_effective_dt
        ,new_audit_effective_dt
        ,old_payee_name
        ,new_payee_name
        ,old_initial_dt
        ,new_initial_dt
        ,old_contact_name
        ,new_contact_name
        ,old_addr_1
        ,new_addr_1
        ,old_addr_2
        ,new_addr_2
        ,old_postal_code
        ,new_postal_code
        ,old_postal_extension_code
        ,new_postal_extension_code
        ,old_city
        ,new_city
        ,old_state_prov_cd
        ,new_state_prov_cd
        ,old_phone_1_number
        ,new_phone_1_number
        ,old_phone_2_number
        ,new_phone_2_number
        ,old_agency_cd
        ,new_agency_cd
        ,old_pay_method_cd
        ,new_pay_method_cd
        ,old_num_days
        ,new_num_days
        ,old_fax_number
        ,new_fax_number
        ,old_phone_1_extention_number
        ,new_phone_1_extention_number
        ,old_phone_2_extention_number
        ,new_phone_2_extention_number
        ,old_off_dt
        ,new_off_dt
        ,old_direct_bill_ind
        ,new_direct_bill_ind
        ,old_release_ind
        ,new_release_ind
        ,old_email_addr
        ,new_email_addr
        ,old_description
        ,new_description
        ,old_mga
        ,new_mga
        ,old_global
        ,new_global
        ,old_payee_responsible_for_filing
        ,new_payee_responsible_for_filing
        ,old_tax_fee_payee 
        ,new_tax_fee_payee 
        ,audit_action 
    )
    select   old.sagitem 
            ,old.audit_staff_cd
            ,new.audit_staff_cd
            ,old.audit_entry_dt
            ,new.audit_entry_dt
            ,old.audit_time
            ,new.audit_time
            ,old.audit_cd
            ,new.audit_cd
            ,old.audit_history_record_number
            ,new.audit_history_record_number
            ,old.audit_program
            ,new.audit_program
            ,old.audit_effective_dt
            ,new.audit_effective_dt
            ,old.payee_name
            ,new.payee_name
            ,old.initial_dt
            ,new.initial_dt
            ,old.contact_name
            ,new.contact_name
            ,old.addr_1
            ,new.addr_1
            ,old.addr_2
            ,new.addr_2
            ,old.postal_code
            ,new.postal_code
            ,old.postal_extension_code
            ,new.postal_extension_code
            ,old.city
            ,new.city
            ,old.state_prov_cd
            ,new.state_prov_cd
            ,old.phone_1_number
            ,new.phone_1_number
            ,old.phone_2_number
            ,new.phone_2_number
            ,old.agency_cd
            ,new.agency_cd
            ,old.pay_method_cd
            ,new.pay_method_cd
            ,old.num_days
            ,new.num_days
            ,old.fax_number
            ,new.fax_number
            ,old.phone_1_extention_number
            ,new.phone_1_extention_number
            ,old.phone_2_extention_number
            ,new.phone_2_extention_number
            ,old.off_dt
            ,new.off_dt
            ,old.direct_bill_ind
            ,new.direct_bill_ind
            ,old.release_ind
            ,new.release_ind
            ,old.email_addr
            ,new.email_addr
            ,old.description
            ,new.description
            ,old.mga
            ,new.mga
            ,old.global
            ,new.global
            ,old.payee_responsible_for_filing
            ,new.payee_responsible_for_filing
            ,old.tax_fee_payee 
            ,new.tax_fee_payee 
            ,'U' ;
    return old;
end;
$$;
go 

/*** PERMISSIONS ***/
alter function sagitta.tr_audit_payees_u() owner to mj_admin;
go 

grant execute on function sagitta.tr_audit_payees_u() to rl_sagitta_x;
go 
