CREATE OR REPLACE FUNCTION sagitta.tr_audit_ba_coverages_u() 
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$

BEGIN 
	INSERT INTO sagitta.audit_ba_coverages (
		 sagitem 
		,old_audit_staff_cd 
		,new_audit_staff_cd 
		,old_audit_entry_dt 
		,new_audit_entry_dt 
		,old_audit_time 
		,new_audit_time 
		,old_audit_cd 
		,new_audit_cd 
		,old_audit_history_record_number 
		,new_audit_history_record_number 
		,old_audit_program 
		,new_audit_program 
		,old_audit_effective_dt 
		,new_audit_effective_dt 
		,old_audit_change_agency_id 
		,new_audit_change_agency_id 
		,old_obsolete_tag_1 
		,new_obsolete_tag_1 
		,old_obsolete_tag_2 
		,new_obsolete_tag_2 
		,old_count_hired_info 
		,new_count_hired_info 
		,old_count_doc_info 						
		,new_count_doc_info 						
		,old_count_comml_audit_addl_cov_info 
		,new_count_comml_audit_addl_cov_info 
		,old_total_premium 
		,new_total_premium 
		,old_policy_agency_id 
		,new_policy_agency_id 
		,old_liability_symbol_1_cd 
		,new_liability_symbol_1_cd 
		,old_liability_symbol_2_cd 
		,new_liability_symbol_2_cd 
		,old_liability_symbol_3_cd 
		,new_liability_symbol_3_cd 
		,old_liability_symbol_4_cd 
		,new_liability_symbol_4_cd 
		,old_liability_symbol_5_cd 
		,new_liability_symbol_5_cd 
		,old_liability_1_limit 
		,new_liability_1_limit 
		,old_liability_2_limit 
		,new_liability_2_limit 
		,old_liability_deductible_amt 
		,new_liability_deductible_amt 
		,old_liability_premium_amt 
		,new_liability_premium_amt 
		,old_property_damage_limit 
		,new_property_damage_limit 
		,old_property_damage_deductible_amt 
		,new_property_damage_deductible_amt 
		,old_property_damage_premium_amt 
		,new_property_damage_premium_amt 
		,old_pip_no_fault_symbol_1_cd 
		,new_pip_no_fault_symbol_1_cd 
		,old_pip_no_fault_symbol_2_cd 
		,new_pip_no_fault_symbol_2_cd 
		,old_pip_no_fault_symbol_3_cd 
		,new_pip_no_fault_symbol_3_cd 
		,old_pip_limit 
		,new_pip_limit 
		,old_pip_deductible_amt 
		,new_pip_deductible_amt 
		,old_pip_premium_amt 
		,new_pip_premium_amt 
		,old_apip_symbol_1_cd 
		,new_apip_symbol_1_cd 
		,old_apip_symbol_2_cd 
		,new_apip_symbol_2_cd 
		,old_apip_limit 
		,new_apip_limit 
		,old_apip_deductible_amt 
		,new_apip_deductible_amt 
		,old_apip_premium_amt 
		,new_apip_premium_amt 
		,old_auto_medical_payments_symbol_1_cd 
		,new_auto_medical_payments_symbol_1_cd 
		,old_auto_medical_payments_symbol_2_cd 
		,new_auto_medical_payments_symbol_2_cd 
		,old_auto_medical_payments_symbol_3_cd 
		,new_auto_medical_payments_symbol_3_cd 
		,old_auto_medical_payments_deductible_amt 
		,new_auto_medical_payments_deductible_amt 
		,old_auto_medical_payments_premium_amt 
		,new_auto_medical_payments_premium_amt 
		,old_uninsured_motorist_symbol_1_cd 
		,new_uninsured_motorist_symbol_1_cd 
		,old_uninsured_motorist_symbol_2_cd 
		,new_uninsured_motorist_symbol_2_cd 
		,old_uninsured_motorist_symbol_3_cd 
		,new_uninsured_motorist_symbol_3_cd 
		,old_underinsured_motorist_1_limit 
		,new_underinsured_motorist_1_limit 
		,old_underinsured_motorist_2_limit 
		,new_underinsured_motorist_2_limit 
		,old_underinsured_motorist_deductible_amt 
		,new_underinsured_motorist_deductible_amt 
		,old_underinsured_pd_limit 
		,new_underinsured_pd_limit 
		,old_underinsured_deductible_pd_limit 
		,new_underinsured_deductible_pd_limit 
		,old_underinsured_premium_pd_amt 
		,new_underinsured_premium_pd_amt 
		,old_towing_and_labor_symbol_1_cd 
		,new_towing_and_labor_symbol_1_cd 
		,old_towing_and_labor_symbol_2_cd 
		,new_towing_and_labor_symbol_2_cd 
		,old_towing_and_labor_symbol_3_cd 
		,new_towing_and_labor_symbol_3_cd 
		,old_towing_and_labor_limit 
		,new_towing_and_labor_limit 
		,old_towing_and_labor_deductible_amt 
		,new_towing_and_labor_deductible_amt 
		,old_towing_and_labor_premium_amt 
		,new_towing_and_labor_premium_amt 
		,old_comprehensive_symbol_1_cd 
		,new_comprehensive_symbol_1_cd 
		,old_comprehensive_symbol_2_cd 
		,new_comprehensive_symbol_2_cd 
		,old_comprehensive_symbol_3_cd 
		,new_comprehensive_symbol_3_cd 
		,old_comprehensive_symbol_4_cd 
		,new_comprehensive_symbol_4_cd 
		,old_comprehensive_limit 
		,new_comprehensive_limit 
		,old_comprehensive_deductible_amt 
		,new_comprehensive_deductible_amt 
		,old_comprehensive_premium_amt 
		,new_comprehensive_premium_amt 
		,old_specified_perils_symbol_1_cd 
		,new_specified_perils_symbol_1_cd 
		,old_specified_perils_symbol_2_cd 
		,new_specified_perils_symbol_2_cd 
		,old_specified_perils_symbol_3_cd 
		,new_specified_perils_symbol_3_cd 
		,old_specified_perils_symbol_4_cd 
		,new_specified_perils_symbol_4_cd 
		,old_specified_perils_limit 
		,new_specified_perils_limit 
		,old_specified_perils_deductible_amt 
		,new_specified_perils_deductible_amt 
		,old_specified_perils_premium_amt 
		,new_specified_perils_premium_amt 
		,old_collision_symbol_1_cd 
		,new_collision_symbol_1_cd 
		,old_collision_symbol_2_cd 
		,new_collision_symbol_2_cd 
		,old_collision_symbol_3_cd 
		,new_collision_symbol_3_cd 
		,old_collision_symbol_4_cd 
		,new_collision_symbol_4_cd 
		,old_collision_limit 
		,new_collision_limit 
		,old_collision_deductible_amt 
		,new_collision_deductible_amt 
		,old_collision_premium_amt 
		,new_collision_premium_amt 
		,old_combined_phsycial_damage_symbol_1_cd 
		,new_combined_phsycial_damage_symbol_1_cd 
		,old_combined_phsycial_damage_symbol_2_cd 
		,new_combined_phsycial_damage_symbol_2_cd 
		,old_combined_phsycial_damage_symbol_3_cd 
		,new_combined_phsycial_damage_symbol_3_cd 
		,old_combined_phsycial_damage_symbol_4_cd 
		,new_combined_phsycial_damage_symbol_4_cd 
		,old_combined_physical_damage_limit 
		,new_combined_physical_damage_limit 
		,old_combined_physical_damage_deductible_amt 
		,new_combined_physical_damage_deductible_amt 
		,old_combined_physical_damage_premium_amt 
		,new_combined_physical_damage_premium_amt 
		,old_off_dt 
		,new_off_dt 
		,old_hired_physical_damage_cost_amt 
		,new_hired_physical_damage_cost_amt 
		,audit_action
	)
	SELECT 	 OLD.sagitem 
			,OLD.audit_staff_cd 
			,NEW.audit_staff_cd 
			,OLD.audit_entry_dt 
			,NEW.audit_entry_dt 
			,OLD.audit_time 
			,NEW.audit_time 
			,OLD.audit_cd 
			,NEW.audit_cd 
			,OLD.audit_history_record_number 
			,NEW.audit_history_record_number 
			,OLD.audit_program 
			,NEW.audit_program 
			,OLD.audit_effective_dt 
			,NEW.audit_effective_dt 
			,OLD.audit_change_agency_id 
			,NEW.audit_change_agency_id 
			,OLD.obsolete_tag_1 
			,NEW.obsolete_tag_1 
			,OLD.obsolete_tag_2 
			,NEW.obsolete_tag_2 
			,OLD.count_hired_info 
			,NEW.count_hired_info 
			,OLD.count_doc_info 						
			,NEW.count_doc_info 						
			,OLD.count_comml_audit_addl_cov_info 
			,NEW.count_comml_audit_addl_cov_info 
			,OLD.total_premium 
			,NEW.total_premium 
			,OLD.policy_agency_id 
			,NEW.policy_agency_id 
			,OLD.liability_symbol_1_cd 
			,NEW.liability_symbol_1_cd 
			,OLD.liability_symbol_2_cd 
			,NEW.liability_symbol_2_cd 
			,OLD.liability_symbol_3_cd 
			,NEW.liability_symbol_3_cd 
			,OLD.liability_symbol_4_cd 
			,NEW.liability_symbol_4_cd 
			,OLD.liability_symbol_5_cd 
			,NEW.liability_symbol_5_cd 
			,OLD.liability_1_limit 
			,NEW.liability_1_limit 
			,OLD.liability_2_limit 
			,NEW.liability_2_limit 
			,OLD.liability_deductible_amt 
			,NEW.liability_deductible_amt 
			,OLD.liability_premium_amt 
			,NEW.liability_premium_amt 
			,OLD.property_damage_limit 
			,NEW.property_damage_limit 
			,OLD.property_damage_deductible_amt 
			,NEW.property_damage_deductible_amt 
			,OLD.property_damage_premium_amt 
			,NEW.property_damage_premium_amt 
			,OLD.pip_no_fault_symbol_1_cd 
			,NEW.pip_no_fault_symbol_1_cd 
			,OLD.pip_no_fault_symbol_2_cd 
			,NEW.pip_no_fault_symbol_2_cd 
			,OLD.pip_no_fault_symbol_3_cd 
			,NEW.pip_no_fault_symbol_3_cd 
			,OLD.pip_limit 
			,NEW.pip_limit 
			,OLD.pip_deductible_amt 
			,NEW.pip_deductible_amt 
			,OLD.pip_premium_amt 
			,NEW.pip_premium_amt 
			,OLD.apip_symbol_1_cd 
			,NEW.apip_symbol_1_cd 
			,OLD.apip_symbol_2_cd 
			,NEW.apip_symbol_2_cd 
			,OLD.apip_limit 
			,NEW.apip_limit 
			,OLD.apip_deductible_amt 
			,NEW.apip_deductible_amt 
			,OLD.apip_premium_amt 
			,NEW.apip_premium_amt 
			,OLD.auto_medical_payments_symbol_1_cd 
			,NEW.auto_medical_payments_symbol_1_cd 
			,OLD.auto_medical_payments_symbol_2_cd 
			,NEW.auto_medical_payments_symbol_2_cd 
			,OLD.auto_medical_payments_symbol_3_cd 
			,NEW.auto_medical_payments_symbol_3_cd 
			,OLD.auto_medical_payments_deductible_amt 
			,NEW.auto_medical_payments_deductible_amt 
			,OLD.auto_medical_payments_premium_amt 
			,NEW.auto_medical_payments_premium_amt 
			,OLD.uninsured_motorist_symbol_1_cd 
			,NEW.uninsured_motorist_symbol_1_cd 
			,OLD.uninsured_motorist_symbol_2_cd 
			,NEW.uninsured_motorist_symbol_2_cd 
			,OLD.uninsured_motorist_symbol_3_cd 
			,NEW.uninsured_motorist_symbol_3_cd 
			,OLD.underinsured_motorist_1_limit 
			,NEW.underinsured_motorist_1_limit 
			,OLD.underinsured_motorist_2_limit 
			,NEW.underinsured_motorist_2_limit 
			,OLD.underinsured_motorist_deductible_amt 
			,NEW.underinsured_motorist_deductible_amt 
			,OLD.underinsured_pd_limit 
			,NEW.underinsured_pd_limit 
			,OLD.underinsured_deductible_pd_limit 
			,NEW.underinsured_deductible_pd_limit 
			,OLD.underinsured_premium_pd_amt 
			,NEW.underinsured_premium_pd_amt 
			,OLD.towing_and_labor_symbol_1_cd 
			,NEW.towing_and_labor_symbol_1_cd 
			,OLD.towing_and_labor_symbol_2_cd 
			,NEW.towing_and_labor_symbol_2_cd 
			,OLD.towing_and_labor_symbol_3_cd 
			,NEW.towing_and_labor_symbol_3_cd 
			,OLD.towing_and_labor_limit 
			,NEW.towing_and_labor_limit 
			,OLD.towing_and_labor_deductible_amt 
			,NEW.towing_and_labor_deductible_amt 
			,OLD.towing_and_labor_premium_amt 
			,NEW.towing_and_labor_premium_amt 
			,OLD.comprehensive_symbol_1_cd 
			,NEW.comprehensive_symbol_1_cd 
			,OLD.comprehensive_symbol_2_cd 
			,NEW.comprehensive_symbol_2_cd 
			,OLD.comprehensive_symbol_3_cd 
			,NEW.comprehensive_symbol_3_cd 
			,OLD.comprehensive_symbol_4_cd 
			,NEW.comprehensive_symbol_4_cd 
			,OLD.comprehensive_limit 
			,NEW.comprehensive_limit 
			,OLD.comprehensive_deductible_amt 
			,NEW.comprehensive_deductible_amt 
			,OLD.comprehensive_premium_amt 
			,NEW.comprehensive_premium_amt 
			,OLD.specified_perils_symbol_1_cd 
			,NEW.specified_perils_symbol_1_cd 
			,OLD.specified_perils_symbol_2_cd 
			,NEW.specified_perils_symbol_2_cd 
			,OLD.specified_perils_symbol_3_cd 
			,NEW.specified_perils_symbol_3_cd 
			,OLD.specified_perils_symbol_4_cd 
			,NEW.specified_perils_symbol_4_cd 
			,OLD.specified_perils_limit 
			,NEW.specified_perils_limit 
			,OLD.specified_perils_deductible_amt 
			,NEW.specified_perils_deductible_amt 
			,OLD.specified_perils_premium_amt 
			,NEW.specified_perils_premium_amt 
			,OLD.collision_symbol_1_cd 
			,NEW.collision_symbol_1_cd 
			,OLD.collision_symbol_2_cd 
			,NEW.collision_symbol_2_cd 
			,OLD.collision_symbol_3_cd 
			,NEW.collision_symbol_3_cd 
			,OLD.collision_symbol_4_cd 
			,NEW.collision_symbol_4_cd 
			,OLD.collision_limit 
			,NEW.collision_limit 
			,OLD.collision_deductible_amt 
			,NEW.collision_deductible_amt 
			,OLD.collision_premium_amt 
			,NEW.collision_premium_amt 
			,OLD.combined_phsycial_damage_symbol_1_cd 
			,NEW.combined_phsycial_damage_symbol_1_cd 
			,OLD.combined_phsycial_damage_symbol_2_cd 
			,NEW.combined_phsycial_damage_symbol_2_cd 
			,OLD.combined_phsycial_damage_symbol_3_cd 
			,NEW.combined_phsycial_damage_symbol_3_cd 
			,OLD.combined_phsycial_damage_symbol_4_cd 
			,NEW.combined_phsycial_damage_symbol_4_cd 
			,OLD.combined_physical_damage_limit 
			,NEW.combined_physical_damage_limit 
			,OLD.combined_physical_damage_deductible_amt 
			,NEW.combined_physical_damage_deductible_amt 
			,OLD.combined_physical_damage_premium_amt 
			,NEW.combined_physical_damage_premium_amt 
			,OLD.off_dt 
			,NEW.off_dt 
			,OLD.hired_physical_damage_cost_amt 
			,NEW.hired_physical_damage_cost_amt 
			,'U';
	RETURN OLD;
END;
$$;
GO 

/*** PERMISSIONS ***/
ALTER FUNCTION sagitta.tr_audit_ba_coverages_u() OWNER TO mj_admin;
GO 

GRANT EXECUTE ON FUNCTION sagitta.tr_audit_ba_coverages_u() TO rl_sagitta_x;
GO 