CREATE OR REPLACE FUNCTION sagitta.tr_audit_policies_d()
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$

BEGIN 
	INSERT INTO sagitta.audit_policies (
		 sagitem
		,old_audit_staff_cd
		,old_audit_entry_dt
		,old_audit_time
		,old_audit_cd
		,old_audit_history_record_number
		,old_audit_program
		,old_audit_effective_dt
		,old_audit_change_agency_id
		,old_policy_number
		,old_named_insured
		,old_bill_to_cd
		,old_client_cd
		,old_policy_remark_text
		,old_insurer_name
		,old_coverage_cd
		,old_canc_nonrenew_renew_ind
		,old_policy_contract_term_cd
		,old_policy_effective_dt
		,old_policy_effective_local_standard_time_ind
		,old_policy_expiration_dt
		,old_policy_expiration_local_standard_time_ind
		,old_policy_original_inception_dt
		,old_binder_effective_dt
		,old_binder_start_time_ind
		,old_binder_expiration_dt
		,old_binder_expiration_time_ind
		,old_bill_type_cd
		,old_binder_purpose_cd
		,old_cancellation_type_cd
		,old_canc_nonrenew_renew_dt
		,old_last_premium_amt
		,old_last_commission_pct
		,old_last_commission_amt
		,old_new_renew_ind
		,old_last_transaction_id
		,old_last_transaction_dt
		,old_producer_1_cd
		,old_producer_2_cd
		,old_producer_3_cd
		,old_written_premium_amt
		,old_written_agcy_commission_amt
		,old_written_producer_commission_amt
		,old_previous_policy_id
		,old_next_policy_id
		,old_annual_premium_amt
		,old_annual_agency_premium_amt
		,old_annual_producer_premium_amt
		,old_division_cd
		,old_state_prov_cd
		,old_last_letter
		,old_audit_term_cd
		,old_servicer_cd
		,old_department_cd
		,old_canc_dt
		,old_canc_reason_cd
		,old_canc_evidence
		,old_reinstate_dt
		,old_reinstate_reason_cd
		,old_countersignature_state_prov_cd
		,old_sic_cd
		,old_date_business_started
		,old_nature_business_cd
		,old_general_info_remark_text
		,old_num_current_addr_yrs
		,old_previous_addr_1
		,old_previous_addr_2
		,old_prevoius_postal_code
		,old_previous_postal_extension_code
		,old_previous_city
		,old_previous_state_prov_cd
		,old_current_residence_dt
		,old_previous_residence_dt
		,old_birth_dt
		,old_tax_id
		,old_num_residents_in_household
		,old_named_individuals
		,old_marital_stats_cd
		,old_occupation_class_cd
		,old_occupation_desc
		,old_length_time_employed
		,old_household_income_amt
		,old_commercial_name
		,old_length_time_with_previous_employee
		,old_length_time_with_current_occupation
		,old_num_vehs_in_household
		,old_length_time_known_by_agent_broker
		,old_auto_club_member_yes_no_cd
		,old_umpd_rejection_yes_ne_cd
		,old_underins_motorist_rejection_yes_no_cd
		,old_any_losses_accidents_convictions_ind_yes_no_cd
		,old_residence_owned_rented_cd
		,old_co_insured_birth_dt
		,old_co_insured_tax_id
		,old_co_insured_marital_status_cd
		,old_co_insured_occupation_class_cd
		,old_co_insured_occupation_desc
		,old_co_insured_length_time_with_current_employer
		,old_co_insured_commercial_name
		,old_co_insured_length_time_with_previous_employer
		,old_co_insured_length_time_current_occupation
		,old_business_income_type_business_cd
		,old_policy_type_cd
		,old_integration_policy_number
		,old_do_not_send_to_insurlink
		,old_payee_cd
		,old_canc_last_dt
		,old_policy_desc
		,old_block_download
		,old_block_archive
		,old_policy_source
		,old_carrier_producer_sub_code
		,old_est_prem_amt
		,old_est_comm_pct
		,old_est_comm_amt
		,old_bor_effective_dt
		,old_bor_expiration_dt
		,old_payment_plan
		,old_insureds_title
		,old_co_insureds_title
		,old_insureds_first_name
		,old_co_insureds_first_name
		,old_insureds_middle_name
		,old_co_insureds_middle_name
		,old_insureds_last_name
		,old_co_insureds_last_name
		,old_insureds_suffix
		,old_co_insureds_suffix
		,audit_action
	)
	SELECT 	 OLD.sagitem
			,OLD.audit_staff_cd
			,OLD.audit_entry_dt
			,OLD.audit_time
			,OLD.audit_cd
			,OLD.audit_history_record_number
			,OLD.audit_program
			,OLD.audit_effective_dt
			,OLD.audit_change_agency_id
			,OLD.policy_number
			,OLD.named_insured
			,OLD.bill_to_cd
			,OLD.client_cd
			,OLD.policy_remark_text
			,OLD.insurer_name
			,OLD.coverage_cd
			,OLD.canc_nonrenew_renew_ind
			,OLD.policy_contract_term_cd
			,OLD.policy_effective_dt
			,OLD.policy_effective_local_standard_time_ind
			,OLD.policy_expiration_dt
			,OLD.policy_expiration_local_standard_time_ind
			,OLD.policy_original_inception_dt
			,OLD.binder_effective_dt
			,OLD.binder_start_time_ind
			,OLD.binder_expiration_dt
			,OLD.binder_expiration_time_ind
			,OLD.bill_type_cd
			,OLD.binder_purpose_cd
			,OLD.cancellation_type_cd
			,OLD.canc_nonrenew_renew_dt
			,OLD.last_premium_amt
			,OLD.last_commission_pct
			,OLD.last_commission_amt
			,OLD.new_renew_ind
			,OLD.last_transaction_id
			,OLD.last_transaction_dt
			,OLD.producer_1_cd
			,OLD.producer_2_cd
			,OLD.producer_3_cd
			,OLD.written_premium_amt
			,OLD.written_agcy_commission_amt
			,OLD.written_producer_commission_amt
			,OLD.previous_policy_id
			,OLD.next_policy_id
			,OLD.annual_premium_amt
			,OLD.annual_agency_premium_amt
			,OLD.annual_producer_premium_amt
			,OLD.division_cd
			,OLD.state_prov_cd
			,OLD.last_letter
			,OLD.audit_term_cd
			,OLD.servicer_cd
			,OLD.department_cd
			,OLD.canc_dt
			,OLD.canc_reason_cd
			,OLD.canc_evidence
			,OLD.reinstate_dt
			,OLD.reinstate_reason_cd
			,OLD.countersignature_state_prov_cd
			,OLD.sic_cd
			,OLD.date_business_started
			,OLD.nature_business_cd
			,OLD.general_info_remark_text
			,OLD.num_current_addr_yrs
			,OLD.previous_addr_1
			,OLD.previous_addr_2
			,OLD.prevoius_postal_code
			,OLD.previous_postal_extension_code
			,OLD.previous_city
			,OLD.previous_state_prov_cd
			,OLD.current_residence_dt
			,OLD.previous_residence_dt
			,OLD.birth_dt
			,OLD.tax_id
			,OLD.num_residents_in_household
			,OLD.named_individuals
			,OLD.marital_stats_cd
			,OLD.occupation_class_cd
			,OLD.occupation_desc
			,OLD.length_time_employed
			,OLD.household_income_amt
			,OLD.commercial_name
			,OLD.length_time_with_previous_employee
			,OLD.length_time_with_current_occupation
			,OLD.num_vehs_in_household
			,OLD.length_time_known_by_agent_broker
			,OLD.auto_club_member_yes_no_cd
			,OLD.umpd_rejection_yes_ne_cd
			,OLD.underins_motorist_rejection_yes_no_cd
			,OLD.any_losses_accidents_convictions_ind_yes_no_cd
			,OLD.residence_owned_rented_cd
			,OLD.co_insured_birth_dt
			,OLD.co_insured_tax_id
			,OLD.co_insured_marital_status_cd
			,OLD.co_insured_occupation_class_cd
			,OLD.co_insured_occupation_desc
			,OLD.co_insured_length_time_with_current_employer
			,OLD.co_insured_commercial_name
			,OLD.co_insured_length_time_with_previous_employer
			,OLD.co_insured_length_time_current_occupation
			,OLD.business_income_type_business_cd
			,OLD.policy_type_cd
			,OLD.integration_policy_number
			,OLD.do_not_send_to_insurlink
			,OLD.payee_cd
			,OLD.canc_last_dt
			,OLD.policy_desc
			,OLD.block_download
			,OLD.block_archive
			,OLD.policy_source
			,OLD.carrier_producer_sub_code
			,OLD.est_prem_amt
			,OLD.est_comm_pct
			,OLD.est_comm_amt
			,OLD.bor_effective_dt
			,OLD.bor_expiration_dt
			,OLD.payment_plan
			,OLD.insureds_title
			,OLD.co_insureds_title
			,OLD.insureds_first_name
			,OLD.co_insureds_first_name
			,OLD.insureds_middle_name
			,OLD.co_insureds_middle_name
			,OLD.insureds_last_name
			,OLD.co_insureds_last_name
			,OLD.insureds_suffix
			,OLD.co_insureds_suffix
			,'D';
	RETURN OLD;
END;
$$;
GO 

/*** PERMISSIONS ***/
ALTER FUNCTION sagitta.tr_audit_policies_d() OWNER TO mj_admin;
GO 

GRANT EXECUTE ON FUNCTION sagitta.tr_audit_policies_d() TO rl_sagitta_x;
GO 
