CREATE OR REPLACE FUNCTION sagitta.tr_audit_policies_i()
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$

BEGIN 
	INSERT INTO sagitta.audit_policies (
		 sagitem
		,new_audit_staff_cd
		,new_audit_entry_dt
		,new_audit_time
		,new_audit_cd
		,new_audit_history_record_number
		,new_audit_program
		,new_audit_effective_dt
		,new_audit_change_agency_id
		,new_policy_number
		,new_named_insured
		,new_bill_to_cd
		,new_client_cd
		,new_policy_remark_text
		,new_insurer_name
		,new_coverage_cd
		,new_canc_nonrenew_renew_ind
		,new_policy_contract_term_cd
		,new_policy_effective_dt
		,new_policy_effective_local_standard_time_ind
		,new_policy_expiration_dt
		,new_policy_expiration_local_standard_time_ind
		,new_policy_original_inception_dt
		,new_binder_effective_dt
		,new_binder_start_time_ind
		,new_binder_expiration_dt
		,new_binder_expiration_time_ind
		,new_bill_type_cd
		,new_binder_purpose_cd
		,new_cancellation_type_cd
		,new_canc_nonrenew_renew_dt
		,new_last_premium_amt
		,new_last_commission_pct
		,new_last_commission_amt
		,new_new_renew_ind
		,new_last_transaction_id
		,new_last_transaction_dt
		,new_producer_1_cd
		,new_producer_2_cd
		,new_producer_3_cd
		,new_written_premium_amt
		,new_written_agcy_commission_amt
		,new_written_producer_commission_amt
		,new_previous_policy_id
		,new_next_policy_id
		,new_annual_premium_amt
		,new_annual_agency_premium_amt
		,new_annual_producer_premium_amt
		,new_division_cd
		,new_state_prov_cd
		,new_last_letter
		,new_audit_term_cd
		,new_servicer_cd
		,new_department_cd
		,new_canc_dt
		,new_canc_reason_cd
		,new_canc_evidence
		,new_reinstate_dt
		,new_reinstate_reason_cd
		,new_countersignature_state_prov_cd
		,new_sic_cd
		,new_date_business_started
		,new_nature_business_cd
		,new_general_info_remark_text
		,new_num_current_addr_yrs
		,new_previous_addr_1
		,new_previous_addr_2
		,new_prevoius_postal_code
		,new_previous_postal_extension_code
		,new_previous_city
		,new_previous_state_prov_cd
		,new_current_residence_dt
		,new_previous_residence_dt
		,new_birth_dt
		,new_tax_id
		,new_num_residents_in_household
		,new_named_individuals
		,new_marital_stats_cd
		,new_occupation_class_cd
		,new_occupation_desc
		,new_length_time_employed
		,new_household_income_amt
		,new_commercial_name
		,new_length_time_with_previous_employee
		,new_length_time_with_current_occupation
		,new_num_vehs_in_household
		,new_length_time_known_by_agent_broker
		,new_auto_club_member_yes_no_cd
		,new_umpd_rejection_yes_ne_cd
		,new_underins_motorist_rejection_yes_no_cd
		,new_any_losses_accidents_convictions_ind_yes_no_cd
		,new_residence_owned_rented_cd
		,new_co_insured_birth_dt
		,new_co_insured_tax_id
		,new_co_insured_marital_status_cd
		,new_co_insured_occupation_class_cd
		,new_co_insured_occupation_desc
		,new_co_insured_length_time_with_current_employer
		,new_co_insured_commercial_name
		,new_co_insured_length_time_with_previous_employer
		,new_co_insured_length_time_current_occupation
		,new_business_income_type_business_cd
		,new_policy_type_cd
		,new_integration_policy_number
		,new_do_not_send_to_insurlink
		,new_payee_cd
		,new_canc_last_dt
		,new_policy_desc
		,new_block_download
		,new_block_archive
		,new_policy_source
		,new_carrier_producer_sub_code
		,new_est_prem_amt
		,new_est_comm_pct
		,new_est_comm_amt
		,new_bor_effective_dt
		,new_bor_expiration_dt
		,new_payment_plan
		,new_insureds_title
		,new_co_insureds_title
		,new_insureds_first_name
		,new_co_insureds_first_name
		,new_insureds_middle_name
		,new_co_insureds_middle_name
		,new_insureds_last_name
		,new_co_insureds_last_name
		,new_insureds_suffix
		,new_co_insureds_suffix
		,audit_action
	)
	SELECT 	 NEW.sagitem
			,NEW.audit_staff_cd
			,NEW.audit_entry_dt
			,NEW.audit_time
			,NEW.audit_cd
			,NEW.audit_history_record_number
			,NEW.audit_program
			,NEW.audit_effective_dt
			,NEW.audit_change_agency_id
			,NEW.policy_number
			,NEW.named_insured
			,NEW.bill_to_cd
			,NEW.client_cd
			,NEW.policy_remark_text
			,NEW.insurer_name
			,NEW.coverage_cd
			,NEW.canc_nonrenew_renew_ind
			,NEW.policy_contract_term_cd
			,NEW.policy_effective_dt
			,NEW.policy_effective_local_standard_time_ind
			,NEW.policy_expiration_dt
			,NEW.policy_expiration_local_standard_time_ind
			,NEW.policy_original_inception_dt
			,NEW.binder_effective_dt
			,NEW.binder_start_time_ind
			,NEW.binder_expiration_dt
			,NEW.binder_expiration_time_ind
			,NEW.bill_type_cd
			,NEW.binder_purpose_cd
			,NEW.cancellation_type_cd
			,NEW.canc_nonrenew_renew_dt
			,NEW.last_premium_amt
			,NEW.last_commission_pct
			,NEW.last_commission_amt
			,NEW.new_renew_ind
			,NEW.last_transaction_id
			,NEW.last_transaction_dt
			,NEW.producer_1_cd
			,NEW.producer_2_cd
			,NEW.producer_3_cd
			,NEW.written_premium_amt
			,NEW.written_agcy_commission_amt
			,NEW.written_producer_commission_amt
			,NEW.previous_policy_id
			,NEW.next_policy_id
			,NEW.annual_premium_amt
			,NEW.annual_agency_premium_amt
			,NEW.annual_producer_premium_amt
			,NEW.division_cd
			,NEW.state_prov_cd
			,NEW.last_letter
			,NEW.audit_term_cd
			,NEW.servicer_cd
			,NEW.department_cd
			,NEW.canc_dt
			,NEW.canc_reason_cd
			,NEW.canc_evidence
			,NEW.reinstate_dt
			,NEW.reinstate_reason_cd
			,NEW.countersignature_state_prov_cd
			,NEW.sic_cd
			,NEW.date_business_started
			,NEW.nature_business_cd
			,NEW.general_info_remark_text
			,NEW.num_current_addr_yrs
			,NEW.previous_addr_1
			,NEW.previous_addr_2
			,NEW.prevoius_postal_code
			,NEW.previous_postal_extension_code
			,NEW.previous_city
			,NEW.previous_state_prov_cd
			,NEW.current_residence_dt
			,NEW.previous_residence_dt
			,NEW.birth_dt
			,NEW.tax_id
			,NEW.num_residents_in_household
			,NEW.named_individuals
			,NEW.marital_stats_cd
			,NEW.occupation_class_cd
			,NEW.occupation_desc
			,NEW.length_time_employed
			,NEW.household_income_amt
			,NEW.commercial_name
			,NEW.length_time_with_previous_employee
			,NEW.length_time_with_current_occupation
			,NEW.num_vehs_in_household
			,NEW.length_time_known_by_agent_broker
			,NEW.auto_club_member_yes_no_cd
			,NEW.umpd_rejection_yes_ne_cd
			,NEW.underins_motorist_rejection_yes_no_cd
			,NEW.any_losses_accidents_convictions_ind_yes_no_cd
			,NEW.residence_owned_rented_cd
			,NEW.co_insured_birth_dt
			,NEW.co_insured_tax_id
			,NEW.co_insured_marital_status_cd
			,NEW.co_insured_occupation_class_cd
			,NEW.co_insured_occupation_desc
			,NEW.co_insured_length_time_with_current_employer
			,NEW.co_insured_commercial_name
			,NEW.co_insured_length_time_with_previous_employer
			,NEW.co_insured_length_time_current_occupation
			,NEW.business_income_type_business_cd
			,NEW.policy_type_cd
			,NEW.integration_policy_number
			,NEW.do_not_send_to_insurlink
			,NEW.payee_cd
			,NEW.canc_last_dt
			,NEW.policy_desc
			,NEW.block_download
			,NEW.block_archive
			,NEW.policy_source
			,NEW.carrier_producer_sub_code
			,NEW.est_prem_amt
			,NEW.est_comm_pct
			,NEW.est_comm_amt
			,NEW.bor_effective_dt
			,NEW.bor_expiration_dt
			,NEW.payment_plan
			,NEW.insureds_title
			,NEW.co_insureds_title
			,NEW.insureds_first_name
			,NEW.co_insureds_first_name
			,NEW.insureds_middle_name
			,NEW.co_insureds_middle_name
			,NEW.insureds_last_name
			,NEW.co_insureds_last_name
			,NEW.insureds_suffix
			,NEW.co_insureds_suffix
			,'I';
	RETURN NEW;
END;
$$;
GO 

/*** PERMISSIONS ***/
ALTER FUNCTION sagitta.tr_audit_policies_i() OWNER TO mj_admin;
GO 

GRANT EXECUTE ON FUNCTION sagitta.tr_audit_policies_i() TO rl_sagitta_x;
GO 
