CREATE OR REPLACE FUNCTION sagitta.tr_audit_insurors_u() 
RETURNS TRIGGER 
LANGUAGE plpgsql 
AS $$

BEGIN 
	INSERT INTO sagitta.audit_insurors (
		 sagitem 
		,old_audit_staff_cd 
		,new_audit_staff_cd 
		,old_audit_entry_dt 
		,new_audit_entry_dt 
		,old_audit_time 
		,new_audit_time 
		,old_audit_cd 
		,new_audit_cd 
		,old_audit_history_record_number 
		,new_audit_history_record_number 
		,old_audit_program 
		,new_audit_program 
		,old_insurer_cd 
		,new_insurer_cd 
		,old_insurer_name 
		,new_insurer_name 
		,old_payee_cd 
		,new_payee_cd 
		,old_addr_1 
		,new_addr_1 
		,old_addr_2 
		,new_addr_2 
		,old_postal_code 
		,new_postal_code 
		,old_postal_extension_code 
		,new_postal_extension_code 
		,old_city 
		,new_city 
		,old_state_prov_cd 
		,new_state_prov_cd 
		,old_telephone_1 
		,new_telephone_1 
		,old_telephone_2 
		,new_telephone_2 
		,old_group 
		,new_group 
		,old_agency_code 
		,new_agency_code 
		,old_phone_extension_1_number 
		,new_phone_extension_1_number 
		,old_company_code 
		,new_company_code 
		,old_phone_extension_2_number 
		,new_phone_extension_2_number 
		,old_naic_cd 
		,new_naic_cd 
		,old_fax_number 
		,new_fax_number 
		,old_type 
		,new_type 
		,old_obsolete_41 
		,new_obsolete_41 
		,old_date_off 
		,new_date_off 
		,old_date_off_remark 
		,new_date_off_remark 
		,old_email_addr 
		,new_email_addr 
		,old_rounding_difference 
		,new_rounding_difference 
		,old_description 
		,new_description 
		,old_global 
		,new_global 
		,old_am_best_number 
		,new_am_best_number 
		,old_bests_financial_strength 
		,new_bests_financial_strength 
		,old_bests_financial_size 
		,new_bests_financial_size 
		,old_state_of_domicile 
		,new_state_of_domicile 
		,old_amb_company_name 
		,new_amb_company_name 
		,old_amb_parent_number 
		,new_amb_parent_number 
		,old_financial_strength_outlook 
		,new_financial_strength_outlook 
		,old_financial_strength_action 
		,new_financial_strength_action 
		,old_fein 
		,new_fein 
		,old_amb_last_update 
		,new_amb_last_update 
		,old_auto_id_claim_reporting_phone_number 
		,new_auto_id_claim_reporting_phone_number 
		,old_auto_id_claim_reporting_phone_extension 
		,new_auto_id_claim_reporting_phone_extension 
		,audit_action 
	)
	SELECT 	 OLD.sagitem 
			,OLD.audit_staff_cd 
			,NEW.audit_staff_cd 
			,OLD.audit_entry_dt 
			,NEW.audit_entry_dt 
			,OLD.audit_time 
			,NEW.audit_time 
			,OLD.audit_cd 
			,NEW.audit_cd 
			,OLD.audit_history_record_number 
			,NEW.audit_history_record_number 
			,OLD.audit_program 
			,NEW.audit_program 
			,OLD.insurer_cd 
			,NEW.insurer_cd 
			,OLD.insurer_name 
			,NEW.insurer_name 
			,OLD.payee_cd 
			,NEW.payee_cd 
			,OLD.addr_1 
			,NEW.addr_1 
			,OLD.addr_2 
			,NEW.addr_2 
			,OLD.postal_code 
			,NEW.postal_code 
			,OLD.postal_extension_code 
			,NEW.postal_extension_code 
			,OLD.city 
			,NEW.city 
			,OLD.state_prov_cd 
			,NEW.state_prov_cd 
			,OLD.telephone_1 
			,NEW.telephone_1 
			,OLD.telephone_2 
			,NEW.telephone_2 
			,OLD.group 
			,NEW.group 
			,OLD.agency_code 
			,NEW.agency_code 
			,OLD.phone_extension_1_number 
			,NEW.phone_extension_1_number 
			,OLD.company_code 
			,NEW.company_code 
			,OLD.phone_extension_2_number 
			,NEW.phone_extension_2_number 
			,OLD.naic_cd 
			,NEW.naic_cd 
			,OLD.fax_number 
			,NEW.fax_number 
			,OLD.type 
			,NEW.type 
			,OLD.obsolete_41 
			,NEW.obsolete_41 
			,OLD.date_off 
			,NEW.date_off 
			,OLD.date_off_remark 
			,NEW.date_off_remark 
			,OLD.email_addr 
			,NEW.email_addr 
			,OLD.rounding_difference 
			,NEW.rounding_difference 
			,OLD.description 
			,NEW.description 
			,OLD.global 
			,NEW.global 
			,OLD.am_best_number 
			,NEW.am_best_number 
			,OLD.bests_financial_strength 
			,NEW.bests_financial_strength 
			,OLD.bests_financial_size 
			,NEW.bests_financial_size 
			,OLD.state_of_domicile 
			,NEW.state_of_domicile 
			,OLD.amb_company_name 
			,NEW.amb_company_name 
			,OLD.amb_parent_number 
			,NEW.amb_parent_number 
			,OLD.financial_strength_outlook 
			,NEW.financial_strength_outlook 
			,OLD.financial_strength_action 
			,NEW.financial_strength_action 
			,OLD.fein 
			,NEW.fein 
			,OLD.amb_last_update 
			,NEW.amb_last_update 
			,OLD.auto_id_claim_reporting_phone_number 
			,NEW.auto_id_claim_reporting_phone_number 
			,OLD.auto_id_claim_reporting_phone_extension 
			,NEW.auto_id_claim_reporting_phone_extension 
			,'U';
	RETURN OLD;
END;
$$;
GO;

/*** PERMISSIONS ***/
ALTER FUNCTION sagitta.tr_audit_insurors_u() OWNER TO mj_admin;
GO 

GRANT EXECUTE ON FUNCTION sagitta.tr_audit_insurors_u() TO rl_sagitta_x;
GO 
