CREATE TABLE IF NOT EXISTS benefitpoint.audit_address (
	 address_source 	TEXT 			NOT NULL 
	,source_type 		TEXT 			NOT NULL 
	,source_key 		TEXT 			NOT NULL 
	,old_street_1 		varchar(100) 	NULL 
	,new_street_1 		varchar(100) 	NULL 
	,old_street_2 		varchar(100) 	NULL  
	,new_street_2 		varchar(100) 	NULL  
	,old_city 			varchar(100) 	NULL 
	,new_city 			varchar(100) 	NULL 
	,old_state 			varchar(100) 	NULL 
	,new_state 			varchar(100) 	NULL 
	,old_zip 			varchar(100) 	NULL 
	,new_zip 			varchar(100) 	NULL 
	,old_country 		varchar(100) 	NULL 
	,new_country 		varchar(100) 	NULL 
	,audit_action 		char(1) 		NOT NULL 
	,audit_user 		TEXT 			NOT NULL 	DEFAULT current_user
	,audit_timestamp 	timestamp 		NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 			bigint 			NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE benefitpoint.audit_address OWNER TO mj_admin;
GO 

GRANT INSERT ON benefitpoint.audit_address TO rl_benefitpoint_a;
GO 
