CREATE TABLE benefitpoint.audit_custom_field_value (
	 old_custom_field_value_id 	int 		NULL 
	,new_custom_field_value_id 	int 		NULL 
	,custom_field_id 			int 		NOT NULL 
	,old_option_value_id 		int 		NULL 
	,new_option_value_id 		int 		NULL 
	,old_value_text 			TEXT 		NULL 
	,new_value_text 			TEXT 		NULL 
	,cfv_source 				TEXT 		NOT NULL 
	,source_key 				int 		NOT NULL 
	,audit_action 				char(1) 	NOT NULL 
	,audit_user 				TEXT 		NOT NULL 	DEFAULT current_user
	,audit_timestamp 			timestamp 	NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 					bigint 		NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE benefitpoint.audit_custom_field_value OWNER TO mj_admin;
GO 

GRANT INSERT ON benefitpoint.audit_custom_field_value TO rl_benefitpoint_a;
GO 
