create table benefitpoint.audit_additional_product_attribute (
     product_id                     int                         not null 
    ,account_id                     int                         not null 
    ,attribute_id                   int                         not null 
    ,old_name                       text                        null 
    ,new_name                       text                        null 
    ,old_field_value_type           text                        null 
    ,new_field_value_type           text                        null 
    ,old_value_num                  double precision            null 
    ,new_value_num                  double precision            null 
    ,old_value_text                 text                        null 
    ,new_value_text                 text                        null 
    ,old_value_date                 timestamp                   null 
    ,new_value_date                 timestamp                   null 
    ,old_option_value_id            int                         null 
    ,new_option_value_id            int                         null 
	,audit_action 		            char(1) 	                NOT NULL 
	,audit_user 		            TEXT 		                NOT NULL 	DEFAULT current_user 
	,audit_timestamp 	            timestamp 	                NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 			            bigint 		                NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
go 

/*** PERMISSIONS ***/
alter table benefitpoint.audit_additional_product_attribute owner to mj_admin;
go 

grant insert on benefitpoint.audit_additional_product_attribute to rl_benefitpoint_a;
go 