CREATE TABLE IF NOT EXISTS benefitpoint.audit_custom_field_option_value (
	 cfov_source 						TEXT 	NOT NULL 
	,source_key 						int 	NOT NULL 
	,custom_field_option_value_id 		int 	NOT NULL 
	,old_description 					TEXT 	NULL 
	,new_description 					TEXT 	NULL 
	,old_active 						bool 	NULL 
	,new_active 						bool 	NULL 
	,old_sort_order 					int 	NULL 
	,new_sort_order 					int 	NULL 
	,old_default_option_value 			bool 	NULL 
	,new_default_option_value 			bool 	NULL 
	,old_code 							TEXT 	NULL
	,new_code 							TEXT 	NULL
	,audit_action 						char(1) 	NOT NULL 
	,audit_user 						TEXT 		NOT NULL 	DEFAULT current_user
	,audit_timestamp 					timestamp 	NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 							bigint 		NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 
	,CONSTRAINT audit_custom_field_option_value_pkey PRIMARY KEY (audit_id)
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE benefitpoint.audit_custom_field_option_value OWNER TO mj_admin;
GO 

GRANT INSERT ON TABLE benefitpoint.audit_custom_field_option_value TO rl_benefitpoint_a;
GO 
