CREATE TABLE IF NOT EXISTS benefitpoint.audit_custom_field(
	 old_custom_section 			TEXT  	NULL 
	,new_custom_section 			TEXT  	NULL 
	,custom_field_id 			    int 	NOT NULL  	
	,old_field_type 				TEXT 	NULL 
	,new_field_type 				TEXT 	NULL 
	,old_field_value_type 			TEXT 	NULL 
	,new_field_value_type 			TEXT 	NULL 
	,old_length 					int 	NULL 
	,new_length 					int 	NULL 
	,old_label 						TEXT 	NULL 
	,new_label 						TEXT 	NULL
	,old_required 					bool 	NULL 
	,new_required 					bool 	NULL 
	,old_active 					bool 	NULL 
	,new_active 					bool 	NULL 
	,old_sort_order 				int 	NULL 
	,new_sort_order 				int 	NULL 
	,old_phi 						bool 	NULL 
	,new_phi 						bool 	NULL 
	,old_sagitta 					bool 	NULL 
	,new_sagitta 					bool 	NULL 
	,old_sagitta_category			TEXT 	NULL 
	,new_sagitta_category			TEXT 	NULL 
	,old_dependent_trigger_id 		int 	NULL 
	,new_dependent_trigger_id 		int 	NULL 
    ,audit_action 					char(1) 	NOT NULL 
    ,audit_user 					TEXT 		NOT NULL 	DEFAULT current_user 
    ,audit_timestamp 				timestamp 	NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
    ,audit_id 						bigint 		NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE benefitpoint.audit_custom_field OWNER TO mj_admin;
GO 

GRANT INSERT ON benefitpoint.audit_custom_field TO rl_benefitpoint_a;
GO 
