CREATE TABLE IF NOT EXISTS sagitta.audit_policies (
	 sagitem												int 		NOT NULL
	,old_audit_staff_cd                                     TEXT    	NULL
	,new_audit_staff_cd                                     TEXT    	NULL
	,old_audit_entry_dt                                     int 		NULL 
	,new_audit_entry_dt                                     int 		NULL 
	,old_audit_time                                         int 		NULL 
	,new_audit_time                                         int 		NULL 
	,old_audit_cd                                           TEXT    	NULL
	,new_audit_cd                                           TEXT    	NULL
	,old_audit_history_record_number                        TEXT    	NULL
	,new_audit_history_record_number                        TEXT    	NULL
	,old_audit_program                                      TEXT    	NULL
	,new_audit_program                                      TEXT    	NULL
	,old_audit_effective_dt                                 TEXT    	NULL
	,new_audit_effective_dt                                 TEXT    	NULL
	,old_audit_change_agency_id                             TEXT    	NULL
	,new_audit_change_agency_id                             TEXT    	NULL
	,old_policy_number                                      TEXT    	NULL
	,new_policy_number                                      TEXT    	NULL
	,old_named_insured                                      TEXT    	NULL
	,new_named_insured                                      TEXT    	NULL
	,old_bill_to_cd                                         TEXT    	NULL
	,new_bill_to_cd                                         TEXT    	NULL
	,old_client_cd                                          TEXT    	NULL
	,new_client_cd                                          TEXT    	NULL
	,old_policy_remark_text                                 TEXT    	NULL
	,new_policy_remark_text                                 TEXT    	NULL
	,old_insurer_name                                       TEXT    	NULL
	,new_insurer_name                                       TEXT    	NULL
	,old_coverage_cd                                        TEXT    	NULL
	,new_coverage_cd                                        TEXT    	NULL
	,old_canc_nonrenew_renew_ind                            TEXT    	NULL
	,new_canc_nonrenew_renew_ind                            TEXT    	NULL
	,old_policy_contract_term_cd                            TEXT    	NULL
	,new_policy_contract_term_cd                            TEXT    	NULL
	,old_policy_effective_dt                                TEXT    	NULL
	,new_policy_effective_dt                                TEXT    	NULL
	,old_policy_effective_local_standard_time_ind           TEXT    	NULL
	,new_policy_effective_local_standard_time_ind           TEXT    	NULL
	,old_policy_expiration_dt                               TEXT    	NULL
	,new_policy_expiration_dt                               TEXT    	NULL
	,old_policy_expiration_local_standard_time_ind          TEXT    	NULL
	,new_policy_expiration_local_standard_time_ind          TEXT    	NULL
	,old_policy_original_inception_dt                       TEXT    	NULL
	,new_policy_original_inception_dt                       TEXT    	NULL
	,old_binder_effective_dt                                TEXT    	NULL
	,new_binder_effective_dt                                TEXT    	NULL
	,old_binder_start_time_ind                              TEXT    	NULL
	,new_binder_start_time_ind                              TEXT    	NULL
	,old_binder_expiration_dt                               TEXT    	NULL
	,new_binder_expiration_dt                               TEXT    	NULL
	,old_binder_expiration_time_ind                         TEXT    	NULL
	,new_binder_expiration_time_ind                         TEXT    	NULL
	,old_bill_type_cd                                       TEXT    	NULL
	,new_bill_type_cd                                       TEXT    	NULL
	,old_binder_purpose_cd                                  TEXT    	NULL
	,new_binder_purpose_cd                                  TEXT    	NULL
	,old_cancellation_type_cd                               TEXT    	NULL
	,new_cancellation_type_cd                               TEXT    	NULL
	,old_canc_nonrenew_renew_dt                             TEXT    	NULL
	,new_canc_nonrenew_renew_dt                             TEXT    	NULL
	,old_last_premium_amt                                   TEXT    	NULL
	,new_last_premium_amt                                   TEXT    	NULL
	,old_last_commission_pct                                TEXT    	NULL
	,new_last_commission_pct                                TEXT    	NULL
	,old_last_commission_amt                                TEXT    	NULL
	,new_last_commission_amt                                TEXT    	NULL
	,old_new_renew_ind                                      TEXT    	NULL
	,new_new_renew_ind                                      TEXT    	NULL
	,old_last_transaction_id                                TEXT    	NULL
	,new_last_transaction_id                                TEXT    	NULL
	,old_last_transaction_dt                                TEXT    	NULL
	,new_last_transaction_dt                                TEXT    	NULL
	,old_producer_1_cd                                      TEXT    	NULL
	,new_producer_1_cd                                      TEXT    	NULL
	,old_producer_2_cd                                      TEXT    	NULL
	,new_producer_2_cd                                      TEXT    	NULL
	,old_producer_3_cd                                      TEXT    	NULL
	,new_producer_3_cd                                      TEXT    	NULL
	,old_written_premium_amt                                TEXT    	NULL
	,new_written_premium_amt                                TEXT    	NULL
	,old_written_agcy_commission_amt                        TEXT    	NULL
	,new_written_agcy_commission_amt                        TEXT    	NULL
	,old_written_producer_commission_amt                    TEXT    	NULL
	,new_written_producer_commission_amt                    TEXT    	NULL
	,old_prevoius_policy_id                                 TEXT    	NULL
	,new_prevoius_policy_id                                 TEXT    	NULL
	,old_next_policy_id                                     TEXT    	NULL
	,new_next_policy_id                                     TEXT    	NULL
	,old_annual_premium_amt                                 TEXT    	NULL
	,new_annual_premium_amt                                 TEXT    	NULL
	,old_annual_agency_premium_amt                          TEXT    	NULL
	,new_annual_agency_premium_amt                          TEXT    	NULL
	,old_annual_producer_premium_amt                        TEXT    	NULL
	,new_annual_producer_premium_amt                        TEXT    	NULL
	,old_division_cd                                        TEXT    	NULL
	,new_division_cd                                        TEXT    	NULL
	,old_state_prov_cd                                      TEXT    	NULL
	,new_state_prov_cd                                      TEXT    	NULL
	,old_last_letter                                        TEXT    	NULL
	,new_last_letter                                        TEXT    	NULL
	,old_audit_term_cd                                      TEXT    	NULL
	,new_audit_term_cd                                      TEXT    	NULL
	,old_servicer_cd                                        TEXT    	NULL
	,new_servicer_cd                                        TEXT    	NULL
	,old_department_cd                                      TEXT    	NULL
	,new_department_cd                                      TEXT    	NULL
	,old_canc_dt                                            TEXT    	NULL
	,new_canc_dt                                            TEXT    	NULL
	,old_canc_reason_cd                                     TEXT    	NULL
	,new_canc_reason_cd                                     TEXT    	NULL
	,old_canc_evidence                                      TEXT    	NULL
	,new_canc_evidence                                      TEXT    	NULL
	,old_reinstate_dt                                       TEXT    	NULL
	,new_reinstate_dt                                       TEXT    	NULL
	,old_reinstate_reason_cd                                TEXT    	NULL
	,new_reinstate_reason_cd                                TEXT    	NULL
	,old_countersignature_state_prov_cd                     TEXT    	NULL
	,new_countersignature_state_prov_cd                     TEXT    	NULL
	,old_sic_cd                                             TEXT    	NULL
	,new_sic_cd                                             TEXT    	NULL
	,old_date_business_started                              TEXT    	NULL
	,new_date_business_started                              TEXT    	NULL
	,old_nature_business_cd                                 TEXT    	NULL
	,new_nature_business_cd                                 TEXT    	NULL
	,old_general_info_remark_text                           TEXT    	NULL
	,new_general_info_remark_text                           TEXT    	NULL
	,old_num_current_addr_yrs                               TEXT    	NULL
	,new_num_current_addr_yrs                               TEXT    	NULL
	,old_previous_addr_1                                    TEXT    	NULL
	,new_previous_addr_1                                    TEXT    	NULL
	,old_previous_addr_2                                    TEXT    	NULL
	,new_previous_addr_2                                    TEXT    	NULL
	,old_prevoius_postal_code                               TEXT    	NULL
	,new_prevoius_postal_code                               TEXT    	NULL
	,old_previous_postal_extension_code                     TEXT    	NULL
	,new_previous_postal_extension_code                     TEXT    	NULL
	,old_previous_city                                      TEXT    	NULL
	,new_previous_city                                      TEXT    	NULL
	,old_previous_state_prov_cd                             TEXT    	NULL
	,new_previous_state_prov_cd                             TEXT    	NULL
	,old_current_residence_dt                               TEXT    	NULL
	,new_current_residence_dt                               TEXT    	NULL
	,old_previous_residence_dt                              TEXT    	NULL
	,new_previous_residence_dt                              TEXT    	NULL
	,old_birth_dt                                           TEXT    	NULL
	,new_birth_dt                                           TEXT    	NULL
	,old_tax_id                                             TEXT    	NULL
	,new_tax_id                                             TEXT    	NULL
	,old_num_residents_in_household                         TEXT    	NULL
	,new_num_residents_in_household                         TEXT    	NULL
	,old_named_individuals                                  TEXT    	NULL
	,new_named_individuals                                  TEXT    	NULL
	,old_marital_stats_cd                                   TEXT    	NULL
	,new_marital_stats_cd                                   TEXT    	NULL
	,old_occupation_class_cd                                TEXT    	NULL
	,new_occupation_class_cd                                TEXT    	NULL
	,old_occupation_desc                                    TEXT    	NULL
	,new_occupation_desc                                    TEXT    	NULL
	,old_length_time_employed                               TEXT    	NULL
	,new_length_time_employed                               TEXT    	NULL
	,old_household_income_amt                               TEXT    	NULL
	,new_household_income_amt                               TEXT    	NULL
	,old_commercial_name                                    TEXT    	NULL
	,new_commercial_name                                    TEXT    	NULL
	,old_length_time_with_previous_employee                 TEXT    	NULL
	,new_length_time_with_previous_employee                 TEXT    	NULL
	,old_length_time_with_current_occupation                TEXT    	NULL
	,new_length_time_with_current_occupation                TEXT    	NULL
	,old_num_vehs_in_household                              TEXT    	NULL
	,new_num_vehs_in_household                              TEXT    	NULL
	,old_length_time_known_by_agent_broker                  TEXT    	NULL
	,new_length_time_known_by_agent_broker                  TEXT    	NULL
	,old_auto_club_member_yes_no_cd                         TEXT    	NULL
	,new_auto_club_member_yes_no_cd                         TEXT    	NULL
	,old_umpd_rejection_yes_ne_cd                           TEXT    	NULL
	,new_umpd_rejection_yes_ne_cd                           TEXT    	NULL
	,old_underins_motorist_rejection_yes_no_cd              TEXT    	NULL
	,new_underins_motorist_rejection_yes_no_cd              TEXT    	NULL
	,old_any_losses_accidents_convictions_ind_yes_no_cd     TEXT    	NULL
	,new_any_losses_accidents_convictions_ind_yes_no_cd     TEXT    	NULL
	,old_residence_owned_rented_cd                          TEXT    	NULL
	,new_residence_owned_rented_cd                          TEXT    	NULL
	,old_co_insured_birth_dt                                TEXT    	NULL
	,new_co_insured_birth_dt                                TEXT    	NULL
	,old_co_insured_tax_id                                  TEXT    	NULL
	,new_co_insured_tax_id                                  TEXT    	NULL
	,old_co_insured_marital_status_cd                       TEXT    	NULL
	,new_co_insured_marital_status_cd                       TEXT    	NULL
	,old_co_insured_occupation_class_cd                     TEXT    	NULL
	,new_co_insured_occupation_class_cd                     TEXT    	NULL
	,old_co_insured_occupation_desc                         TEXT    	NULL
	,new_co_insured_occupation_desc                         TEXT    	NULL
	,old_co_insured_length_time_with_current_employer       TEXT    	NULL
	,new_co_insured_length_time_with_current_employer       TEXT    	NULL
	,old_co_insured_commercial_name                         TEXT    	NULL
	,new_co_insured_commercial_name                         TEXT    	NULL
	,old_co_insured_length_time_with_previous_employer      TEXT    	NULL
	,new_co_insured_length_time_with_previous_employer      TEXT    	NULL
	,old_co_insured_length_time_current_occupation          TEXT    	NULL
	,new_co_insured_length_time_current_occupation          TEXT    	NULL
	,old_business_income_type_business_cd                   TEXT    	NULL
	,new_business_income_type_business_cd                   TEXT    	NULL
	,old_policy_type_cd                                     TEXT    	NULL
	,new_policy_type_cd                                     TEXT    	NULL
	,old_integration_policy_number                          TEXT    	NULL
	,new_integration_policy_number                          TEXT    	NULL
	,old_do_not_send_to_insurlink                           TEXT    	NULL
	,new_do_not_send_to_insurlink                           TEXT    	NULL
	,old_payee_cd                                           TEXT    	NULL
	,new_payee_cd                                           TEXT    	NULL
	,old_canc_last_dt                                       TEXT    	NULL
	,new_canc_last_dt                                       TEXT    	NULL
	,old_policy_desc                                        TEXT    	NULL
	,new_policy_desc                                        TEXT    	NULL
	,old_block_download                                     TEXT    	NULL
	,new_block_download                                     TEXT    	NULL
	,old_block_archive                                      TEXT    	NULL
	,new_block_archive                                      TEXT    	NULL
	,old_policy_source                                      TEXT    	NULL
	,new_policy_source                                      TEXT    	NULL
	,old_carrier_producer_sub_code                          TEXT    	NULL
	,new_carrier_producer_sub_code                          TEXT    	NULL
	,old_est_prem_amt                                       TEXT    	NULL
	,new_est_prem_amt                                       TEXT    	NULL
	,old_est_comm_pct                                       TEXT    	NULL
	,new_est_comm_pct                                       TEXT    	NULL
	,old_est_comm_amt                                       TEXT    	NULL
	,new_est_comm_amt                                       TEXT    	NULL
	,old_bor_effective_dt                                   TEXT    	NULL
	,new_bor_effective_dt                                   TEXT    	NULL
	,old_bor_expiration_dt                                  TEXT    	NULL
	,new_bor_expiration_dt                                  TEXT    	NULL
	,old_payment_plan                                       TEXT    	NULL
	,new_payment_plan                                       TEXT    	NULL
	,old_insureds_title                                     TEXT    	NULL
	,new_insureds_title                                     TEXT    	NULL
	,old_co_insureds_title                                  TEXT    	NULL
	,new_co_insureds_title                                  TEXT    	NULL
	,old_insureds_first_name                                TEXT    	NULL
	,new_insureds_first_name                                TEXT    	NULL
	,old_co_insureds_first_name                             TEXT    	NULL
	,new_co_insureds_first_name                             TEXT    	NULL
	,old_insureds_middle_name                               TEXT    	NULL
	,new_insureds_middle_name                               TEXT    	NULL
	,old_co_insureds_middle_name                            TEXT    	NULL
	,new_co_insureds_middle_name                            TEXT    	NULL
	,old_insureds_last_name                                 TEXT    	NULL
	,new_insureds_last_name                                 TEXT    	NULL
	,old_co_insureds_last_name                              TEXT    	NULL
	,new_co_insureds_last_name                              TEXT    	NULL
	,old_insureds_suffix                                    TEXT    	NULL
	,new_insureds_suffix                                    TEXT    	NULL
	,old_co_insureds_suffix                                 TEXT    	NULL
	,new_co_insureds_suffix                                 TEXT    	NULL
	,audit_action 											char(1) 	NOT NULL 
	,audit_user 											TEXT 		NOT NULL 	DEFAULT current_user
	,audit_timestamp 										timestamp 	NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 												bigint 		NOT NULL 	GENERATED ALWAYS AS IDENTITY 	PRIMARY KEY 
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE sagitta.audit_policies OWNER TO mj_admin;
GO 

GRANT INSERT ON TABLE sagitta.audit_policies TO rl_sagitta_a;
GO 