CREATE TABLE sagitta.audit_ba_coverages (
	 sagitem 										TEXT 		NOT NULL 
	,old_audit_staff_cd 							TEXT 		NULL 
	,new_audit_staff_cd 							TEXT 		NULL 
	,old_audit_entry_dt 							int 		NULL 
	,new_audit_entry_dt 							int 		NULL 
	,old_audit_time 								int 		NULL 
	,new_audit_time 								int 		NULL 
	,old_audit_cd 									TEXT 		NULL 
	,new_audit_cd 									TEXT 		NULL 
	,old_audit_history_record_number 				TEXT 		NULL 
	,new_audit_history_record_number 				TEXT 		NULL 
	,old_audit_program 								TEXT 		NULL 
	,new_audit_program 								TEXT 		NULL 
	,old_audit_effective_dt 						TEXT 		NULL 
	,new_audit_effective_dt 						TEXT 		NULL 
	,old_audit_change_agency_id 					TEXT 		NULL 
	,new_audit_change_agency_id 					TEXT 		NULL 
	,old_obsolete_tag_1 							TEXT 		NULL 
	,new_obsolete_tag_1 							TEXT 		NULL 
	,old_obsolete_tag_2 							TEXT 		NULL 
	,new_obsolete_tag_2 							TEXT 		NULL 
	,old_count_hired_info 							TEXT 		NULL 
	,new_count_hired_info 							TEXT 		NULL 
	,old_count_doc_info 							TEXT 		NULL 
	,new_count_doc_info 							TEXT 		NULL 
	,old_count_comml_audit_addl_cov_info 			TEXT 		NULL 
	,new_count_comml_audit_addl_cov_info 			TEXT 		NULL 
	,old_total_premium 								TEXT 		NULL 
	,new_total_premium 								TEXT 		NULL 
	,old_policy_agency_id 							TEXT 		NULL 
	,new_policy_agency_id 							TEXT 		NULL 
	,old_liability_symbol_1_cd 						TEXT 		NULL 
	,new_liability_symbol_1_cd 						TEXT 		NULL 
	,old_liability_symbol_2_cd 						TEXT 		NULL 
	,new_liability_symbol_2_cd 						TEXT 		NULL 
	,old_liability_symbol_3_cd 						TEXT 		NULL 
	,new_liability_symbol_3_cd 						TEXT 		NULL 
	,old_liability_symbol_4_cd 						TEXT 		NULL 
	,new_liability_symbol_4_cd 						TEXT 		NULL 
	,old_liability_symbol_5_cd 						TEXT 		NULL 
	,new_liability_symbol_5_cd 						TEXT 		NULL 
	,old_liability_1_limit 							TEXT 		NULL 
	,new_liability_1_limit 							TEXT 		NULL 
	,old_liability_2_limit 							TEXT 		NULL 
	,new_liability_2_limit 							TEXT 		NULL 
	,old_liability_deductible_amt 					TEXT 		NULL 
	,new_liability_deductible_amt 					TEXT 		NULL 
	,old_liability_premium_amt 						TEXT 		NULL 
	,new_liability_premium_amt 						TEXT 		NULL 
	,old_property_damage_limit 						TEXT 		NULL 
	,new_property_damage_limit 						TEXT 		NULL 
	,old_property_damage_deductible_amt 			TEXT 		NULL 
	,new_property_damage_deductible_amt 			TEXT 		NULL 
	,old_property_damage_premium_amt 				TEXT 		NULL 
	,new_property_damage_premium_amt 				TEXT 		NULL 
	,old_pip_no_fault_symbol_1_cd 					TEXT 		NULL 
	,new_pip_no_fault_symbol_1_cd 					TEXT 		NULL 
	,old_pip_no_fault_symbol_2_cd 					TEXT 		NULL 
	,new_pip_no_fault_symbol_2_cd 					TEXT 		NULL 
	,old_pip_no_fault_symbol_3_cd 					TEXT 		NULL 
	,new_pip_no_fault_symbol_3_cd 					TEXT 		NULL 
	,old_pip_limit 									TEXT 		NULL 
	,new_pip_limit 									TEXT 		NULL 
	,old_pip_deductible_amt 						TEXT 		NULL 
	,new_pip_deductible_amt 						TEXT 		NULL 
	,old_pip_premium_amt 							TEXT 		NULL 
	,new_pip_premium_amt 							TEXT 		NULL 
	,old_apip_symbol_1_cd 							TEXT 		NULL 
	,new_apip_symbol_1_cd 							TEXT 		NULL 
	,old_apip_symbol_2_cd 							TEXT 		NULL 
	,new_apip_symbol_2_cd 							TEXT 		NULL 
	,old_apip_limit 								TEXT 		NULL 
	,new_apip_limit 								TEXT 		NULL 
	,old_apip_deductible_amt 						TEXT 		NULL 
	,new_apip_deductible_amt 						TEXT 		NULL 
	,old_apip_premium_amt 							TEXT 		NULL 
	,new_apip_premium_amt 							TEXT 		NULL 
	,old_auto_medical_payments_symbol_1_cd 			TEXT 		NULL 
	,new_auto_medical_payments_symbol_1_cd 			TEXT 		NULL 
	,old_auto_medical_payments_symbol_2_cd 			TEXT 		NULL 
	,new_auto_medical_payments_symbol_2_cd 			TEXT 		NULL 
	,old_auto_medical_payments_symbol_3_cd 			TEXT 		NULL 
	,new_auto_medical_payments_symbol_3_cd 			TEXT 		NULL 
	,old_auto_medical_payments_deductible_amt 		TEXT 		NULL 
	,new_auto_medical_payments_deductible_amt 		TEXT 		NULL 
	,old_auto_medical_payments_premium_amt 			TEXT 		NULL 
	,new_auto_medical_payments_premium_amt 			TEXT 		NULL 
	,old_uninsured_motorist_symbol_1_cd 			TEXT 		NULL 
	,new_uninsured_motorist_symbol_1_cd 			TEXT 		NULL 
	,old_uninsured_motorist_symbol_2_cd 			TEXT 		NULL 
	,new_uninsured_motorist_symbol_2_cd 			TEXT 		NULL 
	,old_uninsured_motorist_symbol_3_cd 			TEXT 		NULL 
	,new_uninsured_motorist_symbol_3_cd 			TEXT 		NULL 
	,old_underinsured_motorist_1_limit 				TEXT 		NULL 
	,new_underinsured_motorist_1_limit 				TEXT 		NULL 
	,old_underinsured_motorist_2_limit 				TEXT 		NULL 
	,new_underinsured_motorist_2_limit 				TEXT 		NULL 
	,old_underinsured_motorist_deductible_amt 		TEXT 		NULL 
	,new_underinsured_motorist_deductible_amt 		TEXT 		NULL 
	,old_underinsured_pd_limit 						TEXT 		NULL 
	,new_underinsured_pd_limit 						TEXT 		NULL 
	,old_underinsured_deductible_pd_limit 			TEXT 		NULL 
	,new_underinsured_deductible_pd_limit 			TEXT 		NULL 
	,old_underinsured_premium_pd_amt 				TEXT 		NULL 
	,new_underinsured_premium_pd_amt 				TEXT 		NULL 
	,old_towing_and_labor_symbol_1_cd 				TEXT 		NULL 
	,new_towing_and_labor_symbol_1_cd 				TEXT 		NULL 
	,old_towing_and_labor_symbol_2_cd 				TEXT 		NULL 
	,new_towing_and_labor_symbol_2_cd 				TEXT 		NULL 
	,old_towing_and_labor_symbol_3_cd 				TEXT 		NULL 
	,new_towing_and_labor_symbol_3_cd 				TEXT 		NULL 
	,old_towing_and_labor_limit 					TEXT 		NULL 
	,new_towing_and_labor_limit 					TEXT 		NULL 
	,old_towing_and_labor_deductible_amt 			TEXT 		NULL 
	,new_towing_and_labor_deductible_amt 			TEXT 		NULL 
	,old_towing_and_labor_premium_amt 				TEXT 		NULL 
	,new_towing_and_labor_premium_amt 				TEXT 		NULL 
	,old_comprehensive_symbol_1_cd 					TEXT 		NULL 
	,new_comprehensive_symbol_1_cd 					TEXT 		NULL 
	,old_comprehensive_symbol_2_cd 					TEXT 		NULL 
	,new_comprehensive_symbol_2_cd 					TEXT 		NULL 
	,old_comprehensive_symbol_3_cd 					TEXT 		NULL 
	,new_comprehensive_symbol_3_cd 					TEXT 		NULL 
	,old_comprehensive_symbol_4_cd 					TEXT 		NULL 
	,new_comprehensive_symbol_4_cd 					TEXT 		NULL 
	,old_comprehensive_limit 						TEXT 		NULL 
	,new_comprehensive_limit 						TEXT 		NULL 
	,old_comprehensive_deductible_amt 				TEXT 		NULL 
	,new_comprehensive_deductible_amt 				TEXT 		NULL 
	,old_comprehensive_premium_amt 					TEXT 		NULL 
	,new_comprehensive_premium_amt 					TEXT 		NULL 
	,old_specified_perils_symbol_1_cd 				TEXT 		NULL 
	,new_specified_perils_symbol_1_cd 				TEXT 		NULL 
	,old_specified_perils_symbol_2_cd 				TEXT 		NULL 
	,new_specified_perils_symbol_2_cd 				TEXT 		NULL 
	,old_specified_perils_symbol_3_cd 				TEXT 		NULL 
	,new_specified_perils_symbol_3_cd 				TEXT 		NULL 
	,old_specified_perils_symbol_4_cd 				TEXT 		NULL 
	,new_specified_perils_symbol_4_cd 				TEXT 		NULL 
	,old_specified_perils_limit 					TEXT 		NULL 
	,new_specified_perils_limit 					TEXT 		NULL 
	,old_specified_perils_deductible_amt 			TEXT 		NULL 
	,new_specified_perils_deductible_amt 			TEXT 		NULL 
	,old_specified_perils_premium_amt 				TEXT 		NULL 
	,new_specified_perils_premium_amt 				TEXT 		NULL 
	,old_collision_symbol_1_cd 						TEXT 		NULL 
	,new_collision_symbol_1_cd 						TEXT 		NULL 
	,old_collision_symbol_2_cd 						TEXT 		NULL 
	,new_collision_symbol_2_cd 						TEXT 		NULL 
	,old_collision_symbol_3_cd 						TEXT 		NULL 
	,new_collision_symbol_3_cd 						TEXT 		NULL 
	,old_collision_symbol_4_cd 						TEXT 		NULL 
	,new_collision_symbol_4_cd 						TEXT 		NULL 
	,old_collision_limit 							TEXT 		NULL 
	,new_collision_limit 							TEXT 		NULL 
	,old_collision_deductible_amt 					TEXT 		NULL 
	,new_collision_deductible_amt 					TEXT 		NULL 
	,old_collision_premium_amt 						TEXT 		NULL 
	,new_collision_premium_amt 						TEXT 		NULL 
	,old_combined_phsycial_damage_symbol_1_cd 		TEXT 		NULL 
	,new_combined_phsycial_damage_symbol_1_cd 		TEXT 		NULL 
	,old_combined_phsycial_damage_symbol_2_cd 		TEXT 		NULL 
	,new_combined_phsycial_damage_symbol_2_cd 		TEXT 		NULL 
	,old_combined_phsycial_damage_symbol_3_cd 		TEXT 		NULL 
	,new_combined_phsycial_damage_symbol_3_cd 		TEXT 		NULL 
	,old_combined_phsycial_damage_symbol_4_cd 		TEXT 		NULL 
	,new_combined_phsycial_damage_symbol_4_cd 		TEXT 		NULL 
	,old_combined_physical_damage_limit 			TEXT 		NULL 
	,new_combined_physical_damage_limit 			TEXT 		NULL 
	,old_combined_physical_damage_deductible_amt 	TEXT 		NULL 
	,new_combined_physical_damage_deductible_amt 	TEXT 		NULL 
	,old_combined_physical_damage_premium_amt 		TEXT 		NULL 
	,new_combined_physical_damage_premium_amt 		TEXT 		NULL 
	,old_off_dt 									TEXT 		NULL 
	,new_off_dt 									TEXT 		NULL 
	,old_hired_physical_damage_cost_amt 			TEXT 		NULL 
	,new_hired_physical_damage_cost_amt 			TEXT 		NULL 
	,audit_action 									char(1) 	NOT NULL 
	,audit_user 									TEXT 		NOT NULL 	DEFAULT current_user 
	,audit_timestamp 								timestamp 	NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 										bigint 		NOT NULL 	GENERATED ALWAYS AS IDENTITY 	PRIMARY KEY 
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE sagitta.audit_ba_coverages OWNER TO mj_admin;
GO 

GRANT INSERT ON sagitta.audit_ba_coverages TO rl_sagitta_a;
GO 
