CREATE TABLE sagitta.audit_ba_coverages_hired_info (
	 sagitem 									TEXT 		NOT NULL 
	,lis 										int 		NOT NULL 
	,old_hired_liability_class_cd 				TEXT 		NULL 
	,new_hired_liability_class_cd 				TEXT 		NULL 
	,old_hired_location_agency_id 				TEXT 		NULL 
	,new_hired_location_agency_id 				TEXT 		NULL 
	,old_hired_state_prov_cd 					TEXT 		NULL 
	,new_hired_state_prov_cd 					TEXT 		NULL 
	,old_hired_liability_cost_amt 				TEXT 		NULL 
	,new_hired_liability_cost_amt 				TEXT 		NULL 
	,old_hired_liability_rate 					TEXT 		NULL 
	,new_hired_liability_rate 					TEXT 		NULL 
	,old_hired_physical_damage_rate 			TEXT 		NULL 
	,new_hired_physical_damage_rate 			TEXT 		NULL 
	,old_hired_liability_minimum_yes_no_cd 		TEXT 		NULL 
	,new_hired_liability_minimum_yes_no_cd 		TEXT 		NULL 
	,old_hired_num_vehs 						TEXT 		NULL 
	,new_hired_num_vehs 						TEXT 		NULL 
	,old_hired_comprehensive_deductible_amt 	TEXT 		NULL 
	,new_hired_comprehensive_deductible_amt 	TEXT 		NULL 
	,old_hired_specified_perils_deductible_amt 	TEXT 		NULL 
	,new_hired_specified_perils_deductible_amt 	TEXT 		NULL 
	,old_hired_collision_deductible_amt 		TEXT 		NULL 
	,new_hired_collision_deductible_amt 		TEXT 		NULL 
	,audit_action 								char(1) 	NOT NULL 
	,audit_user 								TEXT 		NOT NULL 	DEFAULT current_user
	,audit_timestamp 							timestamp 	NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 									bigint 		NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE sagitta.audit_ba_coverages_hired_info OWNER TO mj_admin;
GO 

GRANT INSERT ON sagitta.audit_ba_coverages_hired_info TO rl_sagitta_a;
GO 
