DROP TABLE IF EXISTS powerapps.audit_contact;
GO 

CREATE TABLE IF NOT EXISTS powerapps.audit_contact(
	 contact_source 			TEXT 			NOT NULL
	,source_key 				TEXT 			NOT NULL 
	,old_master_contact 		TEXT 			NULL 
	,new_master_contact 		TEXT 			NULL 
	,old_first_name 			TEXT 			NULL 
	,new_first_name 			TEXT 			NULL 
	,old_last_name 				TEXT 			NULL 
	,new_last_name 				TEXT 			NULL 
	,old_contact_type 			TEXT 			NULL 
	,new_contact_type 			TEXT 			NULL 
	,old_parent_account_guid 	uuid 			NULL 
	,new_parent_account_guid 	uuid 			NULL 
	,old_job_title 				varchar(100) 	NULL 
	,new_job_title 				varchar(100) 	NULL 
	,old_preferred_contact 		bool 			NULL 
	,new_preferred_contact 		bool 			NULL 
	,old_gender 				TEXT 			NULL 
	,new_gender 				TEXT 			NULL 
	,old_family_status 			TEXT 			NULL 
	,new_family_status 			TEXT 			NULL 
	,old_spouse_name 			TEXT 			NULL 
	,new_spouse_name 			TEXT 			NULL 
	,old_dob 					date 			NULL 
	,new_dob 					date 			NULL 
	,old_anniversary 			date 			NULL 
	,new_anniversary 			date 			NULL 
	,old_allow_email 			bool 			NULL 
	,new_allow_email 			bool 			NULL 
	,old_follow_email 			bool 			NULL 
	,new_follow_email 			bool 			NULL 
	,old_allow_bulk_email 		bool 			NULL 
	,new_allow_bulk_email 		bool 			NULL 
	,old_allow_phone 			bool 			NULL 
	,new_allow_phone 			bool 			NULL 
	,old_allow_fax 				bool 			NULL 
	,new_allow_fax 				bool 			NULL 
	,old_allow_mail 			bool 			NULL 
	,new_allow_mail 			bool 			NULL 
	,old_description 			varchar(2000) 	NULL 
	,new_description 			varchar(2000) 	NULL 
	,old_contact_owner 			TEXT 			NULL 
	,new_contact_owner 			TEXT 			NULL 
	,old_status 				TEXT 			NULL 
	,new_status 				TEXT 			NULL 
	,old_status_reason 			TEXT 			NULL 
	,new_status_reason 			TEXT 			NULL 
	,guid 					uuid 			NOT NULL 
	,audit_action 			char(1) 		NOT NULL 
	,audit_user 			TEXT 			NOT NULL 	DEFAULT current_user 
	,audit_timestamp 		timestamp 		NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 				bigint 			NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
GO

/*** PERMISSIONS ***/
ALTER TABLE powerapps.audit_contact OWNER TO mj_admin;
GO

GRANT SELECT ON TABLE powerapps.audit_contact TO rl_powerapps_r;
GO

GRANT INSERT ON powerapps.audit_contact TO rl_powerapps_a;
GO