CREATE TABLE IF NOT EXISTS powerapps.audit_account (
     account_source 			    varchar(50) 	NOT NULL 
	,source_key 				    varchar(50) 	NOT NULL 
	,old_account_name 				varchar(200)	NULL 
    ,new_account_name 				varchar(200)	NULL 
	,old_client_code 				varchar(20) 	NULL 
    ,new_client_code 				varchar(20) 	NULL 
	,old_client_category 			TEXT 			NULL 
    ,new_client_category 			TEXT 			NULL 
	,old_pc_client_category 		TEXT 			NULL 
    ,new_pc_client_category 		TEXT 			NULL 
	,old_medical_funding_type 		TEXT 			NULL 
    ,new_medical_funding_type 		TEXT 			NULL 
	,old_enrolled_employees 		int 			NULL 
    ,new_enrolled_employees 		int 			NULL 
	,old_bor_dt 					date 			NULL 
    ,new_bor_dt 					date 			NULL 
	,old_erisa_info					TEXT 			NULL 
    ,new_erisa_info					TEXT 			NULL 
	,old_stop_loss_renew_dt 		date 			NULL 
    ,new_stop_loss_renew_dt 		date 			NULL 
	,old_industry 					TEXT 			NULL 
    ,new_industry 					TEXT 			NULL 
	,old_dba 						varchar(350) 	NULL 
    ,new_dba 						varchar(350) 	NULL 
	,old_eb_primary_sic 			TEXT 			NULL 
    ,new_eb_primary_sic 			TEXT 			NULL 
	,old_pc_primary_sic 			text			NULL 
    ,new_pc_primary_sic 			text			NULL 
	,old_pc_second_sic 				text		 	NULL 
    ,new_pc_second_sic 				text		 	NULL 
	,old_pc_tertiary_sic 			text		 	NULL 
    ,new_pc_tertiary_sic 			text		 	NULL 
	,old_other_subsidiaries 		varchar(500) 	NULL 
    ,new_other_subsidiaries 		varchar(500) 	NULL 
	,old_pc_client_profile 			bool 			NULL 
    ,new_pc_client_profile 			bool 			NULL 
	,old_eb_client_profile 			bool 			NULL 
    ,new_eb_client_profile 			bool 			NULL 
	,old_eb_account_classification 	TEXT 			NULL 
    ,new_eb_account_classification 	TEXT 			NULL 
	,old_client_rev_25k 			bool 			NULL 
    ,new_client_rev_25k 			bool 			NULL 
	,old_revenue_range 				TEXT 			NULL 
    ,new_revenue_range 				TEXT 			NULL 
	,old_ein 						TEXT 			NULL 
    ,new_ein 						TEXT 			NULL 
	,old_naics_description 			TEXT 			NULL 
    ,new_naics_description 			TEXT 			NULL 
	,old_web_url 					varchar(2048) 	NULL 
    ,new_web_url 					varchar(2048) 	NULL 
	,old_parent_account 			TEXT 			NULL 
    ,new_parent_account 			TEXT 			NULL 
	,old_primary_contact 			TEXT 			NULL 
    ,new_primary_contact 			TEXT 			NULL 
	,old_account_owner 				TEXT 			NULL 
    ,new_account_owner 				TEXT 			NULL 
	,old_status_code 				TEXT 			NULL 
    ,new_status_code 				TEXT 			NULL 
	,old_status_reason 				TEXT 			NULL
    ,new_status_reason 				TEXT 			NULL
    ,guid 							uuid 			NOT NULL 
    ,audit_action 					char(1) 		NOT NULL 
    ,audit_user 					TEXT 			NOT NULL 	DEFAULT current_user
    ,audit_timestamp 				timestamp 		NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
    ,audit_id 						bigint 			NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
GO

/*** PERMISSIONS ***/
ALTER TABLE powerapps.audit_account OWNER TO mj_admin;
GO

GRANT SELECT ON TABLE powerapps.audit_account TO rl_powerapps_r;
GO

GRANT INSERT ON powerapps.audit_account TO rl_powerapps_a;
GO