DROP TABLE IF EXISTS powerapps.audit_address;
GO 

CREATE TABLE powerapps.audit_address(
	 address_source 		TEXT 			NOT NULL 
	,source_type 			TEXT 			NOT NULL 
	,source_key 			TEXT 			NOT NULL 
	,source_address_type 	TEXT 			NOT NULL 
	,old_address_type 		TEXT 			NULL
	,new_address_type 		TEXT 			NULL
	,old_street_1 			varchar(200) 	NULL
	,new_street_1 			varchar(200) 	NULL
	,old_street_2 			varchar(200) 	NULL 
	,new_street_2 			varchar(200) 	NULL 
	,old_city 				varchar(200) 	NULL 
	,new_city 				varchar(200) 	NULL 
	,old_state_province 	varchar(200) 	NULL 
	,new_state_province 	varchar(200) 	NULL 
	,old_zip_post_code 		varchar(15) 	NULL 
	,new_zip_post_code 		varchar(15) 	NULL 
	,old_country_region 	varchar(100) 	NULL 
	,new_country_region 	varchar(100) 	NULL 
	,old_address_owner 		varchar(100) 	NULL 
	,new_address_owner 		varchar(100) 	NULL 
	,old_status_cd 			varchar(1000) 	NULL 
	,new_status_cd 			varchar(1000) 	NULL 
	,old_status_reason 		varchar(205) 	NULL 
	,new_status_reason 		varchar(205) 	NULL 
	,guid 					uuid 			NOT NULL
	,audit_action 			char(1) 		NOT NULL 
	,audit_user 			TEXT 			NOT NULL 	DEFAULT current_user
	,audit_timestamp 		timestamp 		NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 				bigint 			NOT NULL 	GENERATED BY DEFAULT AS IDENTITY 	PRIMARY KEY 
);
GO

/*** PERMISSIONS ***/
ALTER TABLE powerapps.audit_address OWNER TO mj_admin;
GO

GRANT SELECT ON TABLE powerapps.audit_address TO rl_powerapps_r;
GO 

GRANT INSERT ON powerapps.audit_address TO rl_powerapps_a;
GO