CREATE TABLE powerapps.audit_prospect(
	 old_propsect_name 							TEXT 			NULL 
    ,new_propsect_name 							TEXT 			NULL 
	,old_account_name 							TEXT 			NULL 
    ,new_account_name 							TEXT 			NULL 
	,old_line_of_business 						TEXT 			NULL 
    ,new_line_of_business 						TEXT 			NULL 
	,old_department 							TEXT 			NULL 
    ,new_department 							TEXT 			NULL 
	,old_primary_contact 						TEXT 			NULL 
    ,new_primary_contact 						TEXT 			NULL 
	,old_est_revenue 							money			NULL 
    ,new_est_revenue 							money			NULL 
	,old_last_activity_date 					date 			NULL 
    ,new_last_activity_date 					date 			NULL 
	,old_nbr_of_activities 						int 			NULL 
    ,new_nbr_of_activities 						int 			NULL 
	,old_nbr_of_activities_last_90 				int 			NULL 
    ,new_nbr_of_activities_last_90 				int 			NULL 
	,old_prospect_401k 							bool 			NULL 
    ,new_prospect_401k 							bool 			NULL 
	,old_active_producer 						TEXT 			NULL 
    ,new_active_producer 						TEXT 			NULL 
	,old_aor_effective_date 					date 			NULL 
    ,new_aor_effective_date 					date 			NULL 
	,old_carrier 								TEXT 			NULL 
    ,new_carrier 								TEXT 			NULL 
	,old_client_category 						char(1)			NULL 
    ,new_client_category 						char(1)			NULL 
	,old_client_onboarding_initiated 			bool 			NULL 
    ,new_client_onboarding_initiated 			bool 			NULL 
	,old_close_prospect_as_lost 				bool 			NULL 
    ,new_close_prospect_as_lost 				bool 			NULL 
	,old_close_prospect_as_won 					bool 			NULL 
    ,new_close_prospect_as_won 					bool 			NULL 
	,old_committed_revenue 						money 			NULL 
    ,new_committed_revenue 						money 			NULL 
	,old_company_estimated_annual_revenue 		money 			NULL 
    ,new_company_estimated_annual_revenue 		money 			NULL 
	,old_cpa_firm 								TEXT 			NULL 
    ,new_cpa_firm 								TEXT 			NULL 
	,old_current_broker 						TEXT 			NULL 
    ,new_current_broker 						TEXT 			NULL 
	,old_current_lost_notes 					TEXT 			NULL 
    ,new_current_lost_notes 					TEXT 			NULL 
	,old_current_mj_client 						bool 			NULL 
    ,new_current_mj_client 						bool 			NULL 
	,old_current_reason_for_lost 				TEXT 			NULL 
    ,new_current_reason_for_lost 				TEXT 			NULL 
	,old_date_of_first_meeting 					date 			NULL 
    ,new_date_of_first_meeting 					date 			NULL 
	,old_date_of_proposal_meeting 				date 			NULL 
    ,new_date_of_proposal_meeting 				date 			NULL 
	,old_estimated_annual_payroll 				money 			NULL 
    ,new_estimated_annual_payroll 				money 			NULL 
	,old_expected_decision_date 				date 			NULL 
    ,new_expected_decision_date 				date 			NULL 
	,old_first_meeting_completed 				bool 			NULL 
    ,new_first_meeting_completed 				bool 			NULL 
	,old_former_mj_client 						bool 			NULL 
    ,new_former_mj_client 						bool 			NULL 
	,old_funding_type 							TEXT 			NULL 
    ,new_funding_type 							TEXT 			NULL 
	,old_japanese_owned_business 				bool 			NULL 
    ,new_japanese_owned_business 				bool 			NULL 
	,old_marketing_account_type 				TEXT 			NULL 
    ,new_marketing_account_type 				TEXT 			NULL 
	,old_marketing_industry_segment 			TEXT 			NULL 
    ,new_marketing_industry_segment 			TEXT 			NULL 
	,old_marketing_lifecycle_stage 				TEXT 			NULL 
    ,new_marketing_lifecycle_stage 				TEXT 			NULL 
	,old_mentor 								TEXT 			NULL 
    ,new_mentor 								TEXT 			NULL 
	,old_mentor_assigned 						bool 			NULL 
    ,new_mentor_assigned 						bool 			NULL 
	,old_number_of_employees 					int 			NULL 
    ,new_number_of_employees 					int 			NULL 
	,old_number_of_locations 					int 			NULL 
    ,new_number_of_locations 					int 			NULL 
	,old_ongoing_discussion 					TEXT 			NULL 
    ,new_ongoing_discussion 					TEXT 			NULL 
	,old_payroll_or_hris_provider 				TEXT 			NULL 
    ,new_payroll_or_hris_provider 				TEXT 			NULL 
	,old_primary_competitor_for_lost_prospect 	TEXT 			NULL 
    ,new_primary_competitor_for_lost_prospect 	TEXT 			NULL 
	,old_producer_1 							TEXT 			NULL 
    ,new_producer_1 							TEXT 			NULL 
	,old_producer_2 							TEXT 			NULL 
    ,new_producer_2 							TEXT 			NULL 
	,old_producer_3 							TEXT 			NULL 
    ,new_producer_3 							TEXT 			NULL 
	,old_producer_split 						bool 			NULL 
    ,new_producer_split 						bool 			NULL 
	,old_proposal_meeting_completed 			bool 			NULL 
    ,new_proposal_meeting_completed 			bool 			NULL 
	,old_prospect_bpf_finished 					bool 			NULL 
    ,new_prospect_bpf_finished 					bool 			NULL 
	,old_propsect_decision 						TEXT 			NULL 
    ,new_propsect_decision 						TEXT 			NULL 
	,old_qualified_revenue 						money 			NULL 
    ,new_qualified_revenue 						money 			NULL 
	,old_recurring_revenue 						bool 			NULL 
    ,new_recurring_revenue 						bool 			NULL 
	,old_renewal_date 							date 			NULL 
    ,new_renewal_date 							date 			NULL 
	,old_request_for_proposal 					bool 			NULL 
    ,new_request_for_proposal 					bool 			NULL 
	,old_revenue_effective_date 				date 			NULL 
    ,new_revenue_effective_date 				date 			NULL 
	,old_scheduled_first_meeting 				bool 			NULL 
    ,new_scheduled_first_meeting 				bool 			NULL 
	,old_scheduled_proposal_meeting 			bool 			NULL 
    ,new_scheduled_proposal_meeting 			bool 			NULL 
	,old_county 								varchar(200) 	NULL 
    ,new_county 								varchar(200) 	NULL 
	,old_premium_volume 						money 			NULL 
    ,new_premium_volume 						money 			NULL 
	,old_ex_mod 								varchar(100) 	NULL 
    ,new_ex_mod 								varchar(100) 	NULL 
	,old_estimated_annual_premium 				money 			NULL 
    ,new_estimated_annual_premium 				money 			NULL 
	,old_drivers 								int 			NULL 
    ,new_drivers 								int 			NULL 
	,old_vehicles 								int 			NULL 
    ,new_vehicles 								int 			NULL 
	,old_mileage 								int 			NULL 
    ,new_mileage 								int 			NULL 
	,old_fiedlity_bond 							varchar(50) 	NULL 
    ,new_fiedlity_bond 							varchar(50) 	NULL 
	,old_pc_self_funded 						bool 			NULL 
    ,new_pc_self_funded 						bool 			NULL 
	,old_cargo_carrier 							TEXT 			NULL 
    ,new_cargo_carrier 							TEXT 			NULL 
	,old_cargo_renewal 							date 			NULL 
    ,new_cargo_renewal 							date 			NULL 
	,old_business_travel_carrier 				TEXT 			NULL 
    ,new_business_travel_carrier 				TEXT 			NULL 
	,old_business_travel_renewal 				date 			NULL 
    ,new_business_travel_renewal 				date 			NULL 
	,old_miedge_industry 						varchar(250) 	NULL 
    ,new_miedge_industry 						varchar(250) 	NULL 
	,old_actuary_firm_name 						TEXT 			NULL 
    ,new_actuary_firm_name 						TEXT 			NULL 
	,old_actuary_contact_name 					TEXT 			NULL 
    ,new_actuary_contact_name 					TEXT 			NULL 
	,old_prospect_owner 						TEXT 			NULL 
    ,new_prospect_owner 						TEXT 			NULL 
	,old_created_on 							timestamp 		NULL 
    ,new_created_on 							timestamp 		NULL 
	,old_created_by 							TEXT 			NULL  
    ,new_created_by 							TEXT 			NULL  
	,old_modified_on 							timestamp 		NULL 
    ,new_modified_on 							timestamp 		NULL 
	,old_modified_by 							TEXT 			NULL  
    ,new_modified_by 							TEXT 			NULL  
	,old_status 								TEXT 			NULL 
    ,new_status 								TEXT 			NULL 
	,old_status_reason 							TEXT 			NULL 
    ,new_status_reason 							TEXT 			NULL 
	,old_prospect_source 						varchar(150) 	NULL 
    ,new_prospect_source 						varchar(150) 	NULL 
	,old_source_key 							varchar(150) 	NULL 
    ,new_source_key 							varchar(150) 	NULL 
	,guid 									uuid 			NOT NULL 
	,audit_action 								char(1) 		NOT NULL 
	,audit_user 								TEXT 			NOT NULL 	DEFAULT current_user 
	,audit_timestamp 							timestamp 		NOT NULL 	DEFAULT timezone('utc'::TEXT, clock_timestamp())
	,audit_id 									bigint 			NOT NULL 	GENERATED ALWAYS AS IDENTITY 	PRIMARY KEY 
);
GO 

/*** PERMISSIONS ***/
ALTER TABLE powerapps.audit_prospect OWNER TO mj_admin;
GO 
GRANT SELECT ON powerapps.audit_prospect TO rl_powerapps_r;
GO 
GRANT INSERT ON powerapps.audit_prospect TO rl_powerapps_a;
GO 