DROP VIEW pc_ops.policies_since_2018;
GO

CREATE OR REPLACE VIEW pc_ops.policies_since_2018
AS SELECT DISTINCT a.sagitem AS item_key,
    a.sagitem AS pol_seq,
    a.client_cd AS client_key,
    replace(e.client_cd, '&amp;amp;amp;'::text, '&'::text) AS client_code,
    replace(e.client_name, '&amp;amp;amp;'::text, '&'::text) AS c_client_name,
    '1967-12-31'::date + a.policy_effective_dt::integer AS eff_date,
    '1967-12-31'::date + a.policy_expiration_dt AS exp_date,
    a.division_cd AS div,
    a.servicer_cd AS serv,
    replace(a.producer_1_cd, '&amp;amp;amp;'::text, '&'::text) AS pol_prime_prod,
    replace(l.coverage_cd, '&amp;amp;amp;'::text, '&'::text) AS cov,
    a.policy_number,
    a.annual_premium_amt::double precision AS annual_premium,
    a.annual_agency_premium_amt::double precision AS annual_agency_comm,
    (a.est_prem_amt::numeric/100)::double precision as est_prem_amt,
    (a.est_comm_amt::numeric/100)::double precision as est_comm_amt,
    a.bill_type_cd AS b_type,
    a.canc_nonrenew_renew_ind AS c_n_r,
    a.canc_nonrenew_renew_dt::integer + '1967-12-31'::date AS cnr_date,
    a.department_cd AS dept,
    replace(m.client_cd, '&amp;amp;amp;'::text, '&'::text) AS billto_code,
    replace(c.insurer_cd, '&amp;amp;amp;'::text, '&'::text) AS insuror,
    replace(c.insurer_name, '&amp;amp;amp;'::text, '&'::text) AS insurer_name,
    replace(d.sagitem, '&amp;amp;amp;'::text, '&'::text) AS pol_payee,
    replace(d.payee_name, '&amp;amp;amp;'::text, '&'::text) AS payname,
    d.agency_cd AS payee_broker,
        CASE
            WHEN a.audit_term_cd = 'A'::text THEN 'Annual'::text
            ELSE
            CASE
                WHEN a.audit_term_cd = 'X'::text THEN 'At Expiration'::text
                ELSE
                CASE
                    WHEN a.audit_term_cd = 'N'::text THEN 'Not Auditable'::text
                    ELSE
                    CASE
                        WHEN a.audit_term_cd = 'M'::text THEN 'Monthly'::text
                        ELSE
                        CASE
                            WHEN a.audit_term_cd = 'O'::text THEN 'Other'::text
                            ELSE NULL::text
                        END
                    END
                END
            END
        END AS audit_name,
    a.audit_term_cd AS audit_code,
    a.business_income_type_business_cd AS type_of_bus,
    n.staff_name AS pol_prime_prod_name,
    a.producer_2_cd AS pol_second_prod,
    o.staff_name AS pol_second_prod_name,
    a.producer_3_cd,
    p.staff_name AS pol_third_prod_name,
    a.policy_remark_text AS misc_remarks,
    a.binder_effective_dt::integer + '1967-12-31'::date AS binder_eff_date,
    a.binder_expiration_dt::integer + '1967-12-31'::date AS binder_exp_date,
    a.bor_effective_dt::integer + '1967-12-31'::date AS bor_eff_date,
    a.bor_expiration_dt::integer + '1967-12-31'::date AS bor_exp_date,
    a.nature_business_cd AS pol_nat_of_bus,
    a.general_info_remark_text AS gen_info_remarks,
    a.previous_policy_id AS prev_pol_seq,
    a.next_policy_id,
    a.policy_desc,
    b.coverage_name,
    q.insurer_cd AS "group",
    q.insurer_name AS group_name,
    'MISSING, NEED TO GET THIS ELSEWHERE'::text AS broker_parent_addl,
    k.sic_id_4_name,
    j.sic_id_2_name,
    j.sic_category_name,
    k.sic_id_4,
    j.sic_id_2,
    COALESCE(i.client_cd, h.client_cd, g.client_cd, f.client_cd, e.client_cd) AS ultimate_parent,
    r.client_exec AS clientexec_addl
   FROM sagitta.policies a
     LEFT JOIN sagitta.coverages l ON a.coverage_cd = l.sagitem
     LEFT JOIN p_and_c.coverage_codes b ON l.coverage_cd = b.coverage_code
     LEFT JOIN sagitta.insurors c ON a.insurer_name::integer = c.sagitem
     LEFT JOIN sagitta.insurors q ON c."group"::integer = q.sagitem
     LEFT JOIN sagitta.payees d ON a.payee_cd = d.sagitem
     LEFT JOIN sagitta.clients e ON a.client_cd = e.sagitem
     LEFT JOIN sagitta.clients_addlinfo r ON a.client_cd = r.sagitem
     LEFT JOIN ( SELECT clients.sagitem,
            clients.audit_staff_cd,
            clients.audit_entry_dt,
            clients.audit_time,
            clients.audit_cd,
            clients.audit_history_record_number,
            clients.audit_program,
            clients.audit_effective_dt,
            clients.audit_change_agency_id,
            clients.client_cd,
            clients.client_name,
            clients.bill_to_code,
            clients.addr_1,
            clients.addr_2,
            clients.postal_code,
            clients.postal_extension_code,
            clients.city,
            clients.state_prov_cd,
            clients.phone_1_number,
            clients.phone_2_number,
            clients.reference_cd,
            clients.status_cd,
            clients.producer_1_cd,
            clients.producer_2_cd,
            clients.producer_3_cd,
            clients.servicer_1_cd,
            clients.servicer_2_cd,
            clients.servicer_3_cd,
            clients.credit_terms,
            clients.source_cd,
            clients.source_dt,
            clients.cat_1_cd,
            clients.cat_2_cd,
            clients.cat_3_cd,
            clients.cat_4_cd,
            clients.cat_5_cd,
            clients.net_commission_pct,
            clients.contact_method,
            clients.sic_cd,
            clients.collection_comments,
            clients.remark_text,
            clients.phone_1_extension_number,
            clients.phone_2_extension_number,
            clients.fax_number,
            clients.pro_sus_cd,
            clients.date_business_started,
            clients.business_nature,
            clients.inspection_contact,
            clients.inspection_phone_number,
            clients.inspection_phone_extension_number,
            clients.accounting_contact,
            clients.accounting_phone_number,
            clients.accounting_phone_extension_number,
            clients.legal_entity_cd,
            clients.email_addr,
            clients.web_site_link,
            clients.division_number,
            clients.parent_client,
            clients.parent_rel_cd,
            clients.relation_client,
            clients.relation_cd,
            clients.fein,
            clients.insp_email,
            clients.acct_email,
            clients.no_members,
            clients.integration_client_name
           FROM sagitta.clients
          WHERE clients.parent_rel_cd = regexp_replace(clients.parent_rel_cd, '[\n\r]+'::text, ' '::text, 'g'::text)) f ON e.parent_rel_cd = f.sagitem::text
     LEFT JOIN ( SELECT clients.sagitem,
            clients.audit_staff_cd,
            clients.audit_entry_dt,
            clients.audit_time,
            clients.audit_cd,
            clients.audit_history_record_number,
            clients.audit_program,
            clients.audit_effective_dt,
            clients.audit_change_agency_id,
            clients.client_cd,
            clients.client_name,
            clients.bill_to_code,
            clients.addr_1,
            clients.addr_2,
            clients.postal_code,
            clients.postal_extension_code,
            clients.city,
            clients.state_prov_cd,
            clients.phone_1_number,
            clients.phone_2_number,
            clients.reference_cd,
            clients.status_cd,
            clients.producer_1_cd,
            clients.producer_2_cd,
            clients.producer_3_cd,
            clients.servicer_1_cd,
            clients.servicer_2_cd,
            clients.servicer_3_cd,
            clients.credit_terms,
            clients.source_cd,
            clients.source_dt,
            clients.cat_1_cd,
            clients.cat_2_cd,
            clients.cat_3_cd,
            clients.cat_4_cd,
            clients.cat_5_cd,
            clients.net_commission_pct,
            clients.contact_method,
            clients.sic_cd,
            clients.collection_comments,
            clients.remark_text,
            clients.phone_1_extension_number,
            clients.phone_2_extension_number,
            clients.fax_number,
            clients.pro_sus_cd,
            clients.date_business_started,
            clients.business_nature,
            clients.inspection_contact,
            clients.inspection_phone_number,
            clients.inspection_phone_extension_number,
            clients.accounting_contact,
            clients.accounting_phone_number,
            clients.accounting_phone_extension_number,
            clients.legal_entity_cd,
            clients.email_addr,
            clients.web_site_link,
            clients.division_number,
            clients.parent_client,
            clients.parent_rel_cd,
            clients.relation_client,
            clients.relation_cd,
            clients.fein,
            clients.insp_email,
            clients.acct_email,
            clients.no_members,
            clients.integration_client_name
           FROM sagitta.clients
          WHERE clients.parent_rel_cd = regexp_replace(clients.parent_rel_cd, '[\n\r]+'::text, ' '::text, 'g'::text)) g ON f.parent_rel_cd::integer = g.sagitem
     LEFT JOIN ( SELECT clients.sagitem,
            clients.audit_staff_cd,
            clients.audit_entry_dt,
            clients.audit_time,
            clients.audit_cd,
            clients.audit_history_record_number,
            clients.audit_program,
            clients.audit_effective_dt,
            clients.audit_change_agency_id,
            clients.client_cd,
            clients.client_name,
            clients.bill_to_code,
            clients.addr_1,
            clients.addr_2,
            clients.postal_code,
            clients.postal_extension_code,
            clients.city,
            clients.state_prov_cd,
            clients.phone_1_number,
            clients.phone_2_number,
            clients.reference_cd,
            clients.status_cd,
            clients.producer_1_cd,
            clients.producer_2_cd,
            clients.producer_3_cd,
            clients.servicer_1_cd,
            clients.servicer_2_cd,
            clients.servicer_3_cd,
            clients.credit_terms,
            clients.source_cd,
            clients.source_dt,
            clients.cat_1_cd,
            clients.cat_2_cd,
            clients.cat_3_cd,
            clients.cat_4_cd,
            clients.cat_5_cd,
            clients.net_commission_pct,
            clients.contact_method,
            clients.sic_cd,
            clients.collection_comments,
            clients.remark_text,
            clients.phone_1_extension_number,
            clients.phone_2_extension_number,
            clients.fax_number,
            clients.pro_sus_cd,
            clients.date_business_started,
            clients.business_nature,
            clients.inspection_contact,
            clients.inspection_phone_number,
            clients.inspection_phone_extension_number,
            clients.accounting_contact,
            clients.accounting_phone_number,
            clients.accounting_phone_extension_number,
            clients.legal_entity_cd,
            clients.email_addr,
            clients.web_site_link,
            clients.division_number,
            clients.parent_client,
            clients.parent_rel_cd,
            clients.relation_client,
            clients.relation_cd,
            clients.fein,
            clients.insp_email,
            clients.acct_email,
            clients.no_members,
            clients.integration_client_name
           FROM sagitta.clients
          WHERE clients.parent_rel_cd = regexp_replace(clients.parent_rel_cd, '[\n\r]+'::text, ' '::text, 'g'::text)) h ON g.parent_rel_cd::integer = h.sagitem
     LEFT JOIN ( SELECT clients.sagitem,
            clients.audit_staff_cd,
            clients.audit_entry_dt,
            clients.audit_time,
            clients.audit_cd,
            clients.audit_history_record_number,
            clients.audit_program,
            clients.audit_effective_dt,
            clients.audit_change_agency_id,
            clients.client_cd,
            clients.client_name,
            clients.bill_to_code,
            clients.addr_1,
            clients.addr_2,
            clients.postal_code,
            clients.postal_extension_code,
            clients.city,
            clients.state_prov_cd,
            clients.phone_1_number,
            clients.phone_2_number,
            clients.reference_cd,
            clients.status_cd,
            clients.producer_1_cd,
            clients.producer_2_cd,
            clients.producer_3_cd,
            clients.servicer_1_cd,
            clients.servicer_2_cd,
            clients.servicer_3_cd,
            clients.credit_terms,
            clients.source_cd,
            clients.source_dt,
            clients.cat_1_cd,
            clients.cat_2_cd,
            clients.cat_3_cd,
            clients.cat_4_cd,
            clients.cat_5_cd,
            clients.net_commission_pct,
            clients.contact_method,
            clients.sic_cd,
            clients.collection_comments,
            clients.remark_text,
            clients.phone_1_extension_number,
            clients.phone_2_extension_number,
            clients.fax_number,
            clients.pro_sus_cd,
            clients.date_business_started,
            clients.business_nature,
            clients.inspection_contact,
            clients.inspection_phone_number,
            clients.inspection_phone_extension_number,
            clients.accounting_contact,
            clients.accounting_phone_number,
            clients.accounting_phone_extension_number,
            clients.legal_entity_cd,
            clients.email_addr,
            clients.web_site_link,
            clients.division_number,
            clients.parent_client,
            clients.parent_rel_cd,
            clients.relation_client,
            clients.relation_cd,
            clients.fein,
            clients.insp_email,
            clients.acct_email,
            clients.no_members,
            clients.integration_client_name
           FROM sagitta.clients
          WHERE clients.parent_rel_cd = regexp_replace(clients.parent_rel_cd, '[\n\r]+'::text, ' '::text, 'g'::text)) i ON h.parent_rel_cd::integer = i.sagitem
     LEFT JOIN ( SELECT clients.sagitem,
            clients.audit_staff_cd,
            clients.audit_entry_dt,
            clients.audit_time,
            clients.audit_cd,
            clients.audit_history_record_number,
            clients.audit_program,
            clients.audit_effective_dt,
            clients.audit_change_agency_id,
            clients.client_cd,
            clients.client_name,
            clients.bill_to_code,
            clients.addr_1,
            clients.addr_2,
            clients.postal_code,
            clients.postal_extension_code,
            clients.city,
            clients.state_prov_cd,
            clients.phone_1_number,
            clients.phone_2_number,
            clients.reference_cd,
            clients.status_cd,
            clients.producer_1_cd,
            clients.producer_2_cd,
            clients.producer_3_cd,
            clients.servicer_1_cd,
            clients.servicer_2_cd,
            clients.servicer_3_cd,
            clients.credit_terms,
            clients.source_cd,
            clients.source_dt,
            clients.cat_1_cd,
            clients.cat_2_cd,
            clients.cat_3_cd,
            clients.cat_4_cd,
            clients.cat_5_cd,
            clients.net_commission_pct,
            clients.contact_method,
            clients.sic_cd,
            clients.collection_comments,
            clients.remark_text,
            clients.phone_1_extension_number,
            clients.phone_2_extension_number,
            clients.fax_number,
            clients.pro_sus_cd,
            clients.date_business_started,
            clients.business_nature,
            clients.inspection_contact,
            clients.inspection_phone_number,
            clients.inspection_phone_extension_number,
            clients.accounting_contact,
            clients.accounting_phone_number,
            clients.accounting_phone_extension_number,
            clients.legal_entity_cd,
            clients.email_addr,
            clients.web_site_link,
            clients.division_number,
            clients.parent_client,
            clients.parent_rel_cd,
            clients.relation_client,
            clients.relation_cd,
            clients.fein,
            clients.insp_email,
            clients.acct_email,
            clients.no_members,
            clients.integration_client_name
           FROM sagitta.clients
          WHERE clients.parent_rel_cd = regexp_replace(clients.parent_rel_cd, '[\n\r]+'::text, ' '::text, 'g'::text)) m ON i.parent_rel_cd::integer = m.sagitem
     LEFT JOIN sagitta.staff n ON a.producer_1_cd = n.sagitem::text
     LEFT JOIN sagitta.staff o ON a.producer_2_cd = o.sagitem::text
     LEFT JOIN sagitta.staff p ON a.producer_3_cd = p.sagitem::text
     LEFT JOIN ( SELECT DISTINCT industry_codes.sic_id_2,
            industry_codes.sic_id_2_name,
            industry_codes.sic_category_name
           FROM p_and_c.industry_codes) j ON "left"(e.sic_cd, 2) = j.sic_id_2
     LEFT JOIN ( SELECT DISTINCT industry_codes.sic_id_4,
            industry_codes.sic_id_4_name
           FROM p_and_c.industry_codes) k ON "left"(e.sic_cd, 4) = k.sic_id_4
  WHERE ('1967-12-31'::date + a.policy_effective_dt::integer) >= '2018-01-01'::date AND a.division_cd = '1'::text AND ("left"(a.department_cd, 2) = ANY (ARRAY['01'::text, '21'::text, '07'::text])) AND c.insurer_cd <> 'MKT'::text AND a.policy_number !~~* '%APP%'::text;
GO

/*** PERMISSIONS ***/
ALTER VIEW pc_ops.policies_since_2018 OWNER TO mj_admin;
GO

Grant select on table pc_ops.policies_since_2018 to rl_pc_data_analyst;
GO

Grant select on table pc_ops.policies_since_2018 to rl_pc_rpa_developer;
GO

Grant select on table pc_ops.policies_since_2018 to rpauser;
GO
GRANT SELECT ON pc_ops.policies_since_2018 to rl_pc_ops_r;
GO

GRANT INSERT ON pc_ops.policies_since_2018 to rl_pc_ops_a;
GO

GRANT UPDATE ON pc_ops.policies_since_2018 to rl_pc_ops_w;
GO

GRANT DELETE ON pc_ops.policies_since_2018 to rl_pc_ops_d;
GO